# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_household_income_gifts.ui'
#
# Created: Fri Apr 22 21:52:28 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AddHouseholdIncomeGifts(object):
    def setupUi(self, AddHouseholdIncomeGifts):
        AddHouseholdIncomeGifts.setObjectName(_fromUtf8("AddHouseholdIncomeGifts"))
        AddHouseholdIncomeGifts.resize(432, 380)
        self.formLayout_2 = QtGui.QFormLayout(AddHouseholdIncomeGifts)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(AddHouseholdIncomeGifts)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lblHouseholdName = QtGui.QLabel(AddHouseholdIncomeGifts)
        self.lblHouseholdName.setObjectName(_fromUtf8("lblHouseholdName"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblHouseholdName)
        self.label_2 = QtGui.QLabel(AddHouseholdIncomeGifts)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cmbSourceOfTransfer = QtGui.QComboBox(AddHouseholdIncomeGifts)
        self.cmbSourceOfTransfer.setEditable(True)
        self.cmbSourceOfTransfer.setObjectName(_fromUtf8("cmbSourceOfTransfer"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbSourceOfTransfer)
        self.label_4 = QtGui.QLabel(AddHouseholdIncomeGifts)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.txtCash = QtGui.QLineEdit(AddHouseholdIncomeGifts)
        self.txtCash.setObjectName(_fromUtf8("txtCash"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtCash)
        self.groupBox = QtGui.QGroupBox(AddHouseholdIncomeGifts)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cmbFoodType = QtGui.QComboBox(self.groupBox)
        self.cmbFoodType.setEditable(True)
        self.cmbFoodType.setObjectName(_fromUtf8("cmbFoodType"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbFoodType)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.txtUnitOfMeasure = QtGui.QLineEdit(self.groupBox)
        self.txtUnitOfMeasure.setObjectName(_fromUtf8("txtUnitOfMeasure"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtUnitOfMeasure)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_5)
        self.txtUnitsConsumed = QtGui.QLineEdit(self.groupBox)
        self.txtUnitsConsumed.setObjectName(_fromUtf8("txtUnitsConsumed"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtUnitsConsumed)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_6)
        self.txtUnitsSold = QtGui.QLineEdit(self.groupBox)
        self.txtUnitsSold.setObjectName(_fromUtf8("txtUnitsSold"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.txtUnitsSold)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txtUnitPrice = QtGui.QLineEdit(self.groupBox)
        self.txtUnitPrice.setObjectName(_fromUtf8("txtUnitPrice"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.txtUnitPrice)
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.SpanningRole, self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(AddHouseholdIncomeGifts)
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdSave = QtGui.QPushButton(self.groupBox_2)
        self.cmdSave.setDefault(True)
        self.cmdSave.setObjectName(_fromUtf8("cmdSave"))
        self.horizontalLayout.addWidget(self.cmdSave)
        self.cmdCancel = QtGui.QPushButton(self.groupBox_2)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.SpanningRole, self.groupBox_2)
        self.label_2.setBuddy(self.cmbSourceOfTransfer)
        self.label_4.setBuddy(self.txtCash)
        self.label_3.setBuddy(self.cmbFoodType)
        self.label_7.setBuddy(self.txtUnitOfMeasure)
        self.label_5.setBuddy(self.txtUnitsConsumed)
        self.label_6.setBuddy(self.txtUnitsSold)
        self.label_8.setBuddy(self.txtUnitPrice)

        self.retranslateUi(AddHouseholdIncomeGifts)
        QtCore.QObject.connect(self.cmbFoodType, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), AddHouseholdIncomeGifts.displayUnitOfMeasure)
        QtCore.QObject.connect(self.cmdSave, QtCore.SIGNAL(_fromUtf8("clicked()")), AddHouseholdIncomeGifts.saveIncome)
        QtCore.QObject.connect(self.cmdCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), AddHouseholdIncomeGifts.mdiClose)
        QtCore.QMetaObject.connectSlotsByName(AddHouseholdIncomeGifts)
        AddHouseholdIncomeGifts.setTabOrder(self.cmbSourceOfTransfer, self.txtCash)
        AddHouseholdIncomeGifts.setTabOrder(self.txtCash, self.cmbFoodType)
        AddHouseholdIncomeGifts.setTabOrder(self.cmbFoodType, self.txtUnitOfMeasure)
        AddHouseholdIncomeGifts.setTabOrder(self.txtUnitOfMeasure, self.txtUnitsConsumed)
        AddHouseholdIncomeGifts.setTabOrder(self.txtUnitsConsumed, self.txtUnitsSold)
        AddHouseholdIncomeGifts.setTabOrder(self.txtUnitsSold, self.txtUnitPrice)

    def retranslateUi(self, AddHouseholdIncomeGifts):
        AddHouseholdIncomeGifts.setWindowTitle(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Add Transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Household Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHouseholdName.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "{householdname}", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Source of Transfer:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Cash per Year:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Food Transfer", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Food Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Units Consumed:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Units Sold:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Price per Unit:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSave.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancel.setText(QtGui.QApplication.translate("AddHouseholdIncomeGifts", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

