# -*- coding: utf-8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.dialects.mysql import *

metadata = MetaData()


absencefromhousehold = Table('absencefromhousehold', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'percentageaway', Float(asdecimal=True), nullable=False),
    Column(u'reason', VARCHAR(length=200), nullable=False),
    Column(u'whereto', VARCHAR(length=200), nullable=False),
    Column(u'personid', VARCHAR(length=20), nullable=False),
    Column(u'hhid', INTEGER(), nullable=False),
    Column(u'pid', INTEGER(), nullable=False),
    ForeignKeyConstraint([u'personid', u'hhid', u'pid'],
                         [u'householdmembers.personid',
                          u'householdmembers.hhid',
                          u'householdmembers.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_absencefromhousehold_householdmembers1'),
    )


assets = Table('assets', metadata,
    Column(u'assetid', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'assetcategory', VARCHAR(length=255), nullable=False),
    Column(u'assettype', VARCHAR(length=100), nullable=False),
    Column(u'unitofmeasure', VARCHAR(length=45), nullable=False),
    Column(u'unitcost', Float(asdecimal=True), nullable=False),
    Column(u'totalunits', Float(asdecimal=True), nullable=False),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_assets_households1'),
    )


assettypes = Table('assettypes', metadata,
    Column(u'assettype', VARCHAR(length=100), primary_key=True, nullable=False),
    )


creditandloans = Table('creditandloans', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'creditsource', VARCHAR(length=200)),
    Column(u'unit', VARCHAR(length=45)),
    Column(u'creditvalue', Float(asdecimal=True)),
    Column(u'credituse', VARCHAR(length=200)),
    )


cropincome = Table('cropincome', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'incomesource', VARCHAR(length=200)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    Column(u'unitsproduced', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitssold', Float(asdecimal=True)),
    Column(u'unitprice', Float(asdecimal=True)),
    Column(u'otheruses', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitsconsumed', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'preferenceprice', Float(asdecimal=True), default=text(u"'100'")),
    Column(u'preferenceproduction', Float(asdecimal=True), default=text(u"'100'")),
    ForeignKeyConstraint([u'hhid', u'pid'], 
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_cropincome_households1'),
    )


currencies = Table('currencies', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'currencyname', VARCHAR(length=250), nullable=False),
    Column(u'abbreviation', VARCHAR(length=45), nullable=False),
    Column(u'symbol', VARCHAR(length=45)),
    )


dbupdate = Table('dbupdate', metadata,
    Column(u'lastupdate', VARCHAR(length=50), primary_key=True, nullable=False),
    )


diet = Table('diet', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'fooditem', VARCHAR(length=45), nullable=False),
    Column(u'unitofmeasure', VARCHAR(length=45), nullable=False),
    Column(u'percentage', Float(asdecimal=True), nullable=False),
    Column(u'priceperunit', Float(asdecimal=True), nullable=False),
    Column(u'modelprice', Float(asdecimal=True), nullable=False, default=text(u"'0'")),
    ForeignKeyConstraint([u'pid'],
                         [u'projects.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_diet_projects1'),
    )


employmentincome = Table('employmentincome', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'incomesource', VARCHAR(length=200)),
    Column(u'foodtypepaid', VARCHAR(length=200)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    Column(u'unitspaid', Float(asdecimal=True)),
    Column(u'incomekcal', Float(asdecimal=True)),
    Column(u'cashincome', Float(asdecimal=True)),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'preferenceincome', Float(asdecimal=True), default=text(u"'100'")),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_employmentincome_households1'),
    )


expenditure = Table('expenditure', metadata,
    Column(u'expid', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'exptype', VARCHAR(length=100)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    Column(u'priceperunit', Float(asdecimal=True)),
    Column(u'kcalperunit', Float(asdecimal=True)),
    Column(u'totalunits', Float(asdecimal=True)),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_expenditure_households1'),
    )


globalcharacteristics = Table('globalcharacteristics', metadata,
    Column(u'characteristic', VARCHAR(length=250), primary_key=True, nullable=False),
    Column(u'chartype', VARCHAR(length=50), nullable=False),
    Column(u'datatype', INTEGER(), nullable=False),
    Column(u'description', VARCHAR(length=250)),
    )


globalhouseholdcharacteristics = Table('globalhouseholdcharacteristics', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'characteristic', VARCHAR(length=250), nullable=False),
    Column(u'datatype', INTEGER(), nullable=False),
    Column(u'description', VARCHAR(length=250)),
    )


globalpersonalcharacteristics = Table('globalpersonalcharacteristics', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'characteristic', VARCHAR(length=250)),
    Column(u'datatype', INTEGER()),
    Column(u'description', VARCHAR(length=250)),
    )


householdcharacteristics = Table('householdcharacteristics', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'characteristic', VARCHAR(length=250), primary_key=True, nullable=False),
    Column(u'charvalue', VARCHAR(length=255), nullable=False),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_householdcharacteristics_households1'),
    )


householdmembers = Table('householdmembers', metadata,
    Column(u'personid', VARCHAR(length=20), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'headofhousehold', Enum(u'Yes', u'No'), nullable=False),
    Column(u'yearofbirth', INTEGER(), nullable=False),
    Column(u'sex', Enum(u'Male', u'Female'), nullable=False),
    Column(u'education', VARCHAR(length=200)),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'periodaway', INTEGER(), default=text(u"'0'")),
    Column(u'reason', VARCHAR(length=200)),
    Column(u'whereto', VARCHAR(length=200)),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_householdmembers_households1'),
    )


households = Table('households', metadata,
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'householdname', VARCHAR(length=100), nullable=False),
    Column(u'totalassetvalue', Float(asdecimal=True), nullable=False, default=text(u"'0'")),
    Column(u'totalincomevalue', Float(asdecimal=True), nullable=False, default=text(u"'0'")),
    Column(u'totalexpenditure', Float(asdecimal=True), nullable=False, default=text(u"'0'")),
    Column(u'dateofcollection', DATE(), nullable=False),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    ForeignKeyConstraint([u'pid'],
                         [u'projects.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_households_projects1'),
    )


incomeseasonality = Table('incomeseasonality', metadata,
    Column(u'incometype', VARCHAR(length=45), primary_key=True, nullable=False),
    Column(u'jan', Float(asdecimal=True), nullable=False),
    Column(u'feb', Float(asdecimal=True), nullable=False),
    Column(u'mar', Float(asdecimal=True), nullable=False),
    Column(u'apr', Float(asdecimal=True), nullable=False),
    Column(u'may', Float(asdecimal=True), nullable=False),
    Column(u'jun', Float(asdecimal=True), nullable=False),
    Column(u'jul', Float(asdecimal=True), nullable=False),
    Column(u'aug', Float(asdecimal=True), nullable=False),
    Column(u'sep', Float(asdecimal=True), nullable=False),
    Column(u'oct', Float(asdecimal=True), nullable=False),
    Column(u'nov', Float(asdecimal=True), nullable=False),
    Column(u'dec', Float(asdecimal=True), nullable=False),
    )


livestockincome = Table('livestockincome', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'incomesource', VARCHAR(length=200)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    Column(u'unitsproduced', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitssold', Float(asdecimal=True)),
    Column(u'unitprice', Float(asdecimal=True)),
    Column(u'otheruses', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitsconsumed', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'preferenceprice', Float(asdecimal=True), default=text(u"'100'")),
    Column(u'preferenceproduction', Float(asdecimal=True), default=text(u"'100'")),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_livestockincome_households1'),
    )


lookup_energy_needs = Table('lookup_energy_needs', metadata,
    Column(u'age', INTEGER(), primary_key=True, nullable=False),
    Column(u'kCalNeedM', INTEGER()),
    Column(u'kCalNeedF', INTEGER()),
    )


personalcharacteristics = Table('personalcharacteristics', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'personid', VARCHAR(length=20), primary_key=True, nullable=False),
    Column(u'characteristic', VARCHAR(length=250), primary_key=True, nullable=False),
    Column(u'charvalue', VARCHAR(length=255), nullable=False),
    ForeignKeyConstraint([u'personid', u'hhid', u'pid'],
                         [u'householdmembers.personid',
                          u'householdmembers.hhid',
                          u'householdmembers.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_personalcharacteristics_householdmembers1'),
    )


projectassets = Table('projectassets', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'assetname', VARCHAR(length=255), primary_key=True, nullable=False),
    Column(u'assettype', VARCHAR(length=45), nullable=False),
    ForeignKeyConstraint([u'pid'],
                         [u'projects.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'pid'),
    Index(u'pid',
          u'pid',
          unique=False),
    )


projectcharacteristics = Table('projectcharacteristics', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'characteristic', VARCHAR(length=250), primary_key=True, nullable=False),
    Column(u'chartype', VARCHAR(length=50), nullable=False),
    Column(u'datatype', INTEGER(), nullable=False),
    ForeignKeyConstraint([u'pid'],
                         [u'projects.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_projectcharacteristics_projects1'),
    )


projectincomesources = Table('projectincomesources', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'incomesource', VARCHAR(length=255), primary_key=True, nullable=False),
    Column(u'incometype', VARCHAR(length=45), primary_key=True, nullable=False),
    ForeignKeyConstraint([u'pid'],
                         [u'projects.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_projectincomesources_projects'),
    Index(u'fk_projectincomesources_projects',
          u'pid',
          unique=False),
    )


projects = Table('projects', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'projectname', VARCHAR(length=100), nullable=False),
    Column(u'startdate', DATE(), nullable=False),
    Column(u'enddate', DATE(), nullable=False),
    Column(u'description', TEXT(), nullable=False),
    Column(u'currency', TEXT(), nullable=False),
    )


savingscategories = Table('savingscategories', metadata,
    Column(u'savingscategory', VARCHAR(length=100), primary_key=True, nullable=False),
    )


setup_assets = Table('setup_assets', metadata,
    Column(u'assetname', VARCHAR(length=255), primary_key=True, nullable=False),
    Column(u'assettype', VARCHAR(length=50), nullable=False),
    Column(u'unitofmeasure', VARCHAR(length=45), nullable=False),
    )


setup_crops = Table('setup_crops', metadata,
    Column(u'foodtype', VARCHAR(length=100), primary_key=True, nullable=False),
    Column(u'energyvalueperunit', Float(asdecimal=True)),
    Column(u'measuringunit', VARCHAR(length=45)),
    )


setup_employment = Table('setup_employment', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'incomesource', VARCHAR(length=200)),
    )


setup_expenditurecategories = Table('setup_expenditurecategories', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'expenditurecategory', VARCHAR(length=200)),
    )


setup_expendituretypes = Table('setup_expendituretypes', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'expendituretype', VARCHAR(length=200)),
    )


setup_foods_crops = Table('setup_foods_crops', metadata,
    Column(u'name', VARCHAR(length=200), primary_key=True, nullable=False),
    Column(u'category', VARCHAR(length=200), nullable=False),
    Column(u'energyvalueperunit', Float(asdecimal=True)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    )


setup_landtypes = Table('setup_landtypes', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'landtype', VARCHAR(length=200)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    )


setup_livestock = Table('setup_livestock', metadata,
    Column(u'incomesource', VARCHAR(length=200), primary_key=True, nullable=False, default=text(u"''")),
    Column(u'energyvalueperunit', Float(asdecimal=True)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    )


setup_standardofliving = Table('setup_standardofliving', metadata,
    Column(u'item', VARCHAR(length=255), primary_key=True, nullable=False),
    Column(u'type', Enum(u'Household', u'Person', u'Both'), nullable=False),
    )


setup_tradablegoods = Table('setup_tradablegoods', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'tradablegoodtype', VARCHAR(length=200), nullable=False),
    Column(u'unitofmeasure', VARCHAR(length=45), nullable=False),
    )


setup_transfers = Table('setup_transfers', metadata,
    Column(u'assistancetype', VARCHAR(length=200), primary_key=True, nullable=False),
    Column(u'sourceoftransfer', VARCHAR(length=200), primary_key=True, nullable=False),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    )


setup_transfersources = Table('setup_transfersources', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'sourcetype', Enum(u'Internal', u'External'), nullable=False),
    )


setup_treetypes = Table('setup_treetypes', metadata,
    Column(u'treetype', VARCHAR(length=100), primary_key=True, nullable=False),
    Column(u'measuringunit', VARCHAR(length=45)),
    )


setup_wildfoods = Table('setup_wildfoods', metadata,
    Column(u'incomesource', VARCHAR(length=200), primary_key=True, nullable=False, default=text(u"''")),
    Column(u'energyvalueperunit', Float(asdecimal=True)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    )


standardofliving = Table('standardofliving', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'summary', VARCHAR(length=255), primary_key=True, nullable=False),
    Column(u'scope', Enum(u'Household', u'Person'), nullable=False),
    Column(u'gender', Enum(u'Male', u'Female', u'All')),
    Column(u'agebottom', INTEGER(), default=text(u"'0'")),
    Column(u'agetop', INTEGER(), default=text(u"'0'")),
    Column(u'item', VARCHAR(length=255), nullable=False),
    Column(u'costperyear', Float(asdecimal=True), nullable=False),
    Column(u'modelprice', Float(asdecimal=True), default=text(u"'0'")),
    ForeignKeyConstraint([u'pid'],
                         [u'projects.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_standardofliving_projects1'),
    Index(u'fk_standardofliving_projects1',
          u'pid',
          unique=False),
    )


transferlog = Table('transferlog', metadata,
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'pid_access', INTEGER(), nullable=False),
    Column(u'projectname', VARCHAR(length=45), nullable=False),
    Column(u'datecollected', VARCHAR(length=45), nullable=False),
    Column(u'currency', VARCHAR(length=45), nullable=False),
    ForeignKeyConstraint([u'pid'],
                         [u'projects.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_transferlog_projects1'),
    )


transfers = Table('transfers', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'sourcetype', Enum(u'Internal', u'External'), nullable=False),
    Column(u'sourceoftransfer', VARCHAR(length=255), nullable=False),
    Column(u'cashperyear', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'foodtype', VARCHAR(length=255)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    Column(u'unitsgiven', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitsconsumed', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitssold', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'priceperunit', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'preferenceprice', Float(asdecimal=True), default=text(u"'100'")),
    Column(u'preferenceproduction', Float(asdecimal=True), default=text(u"'100'")),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_transfers_households1'),
    )


wildfoods = Table('wildfoods', metadata,
    Column(u'id', INTEGER(), primary_key=True, nullable=False),
    Column(u'hhid', INTEGER(), primary_key=True, nullable=False),
    Column(u'incomesource', VARCHAR(length=200)),
    Column(u'unitofmeasure', VARCHAR(length=45)),
    Column(u'unitsproduced', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitssold', Float(asdecimal=True)),
    Column(u'unitprice', Float(asdecimal=True)),
    Column(u'otheruses', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'unitsconsumed', Float(asdecimal=True), default=text(u"'0'")),
    Column(u'pid', INTEGER(), primary_key=True, nullable=False),
    Column(u'preferenceprice', Float(asdecimal=True), default=text(u"'100'")),
    Column(u'preferenceproduction', Float(asdecimal=True), default=text(u"'100'")),
    ForeignKeyConstraint([u'hhid', u'pid'],
                         [u'households.hhid',
                          u'households.pid'],
                         ondelete='CASCADE', onupdate='CASCADE',
                         name=u'fk_wildfoods_households1'),
    )

