# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_expendituretypes.ui'
#
# Created: Fri Apr 22 14:52:25 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ExpenditureTypes(object):
    def setupUi(self, ExpenditureTypes):
        ExpenditureTypes.setObjectName(_fromUtf8("ExpenditureTypes"))
        ExpenditureTypes.resize(485, 329)
        ExpenditureTypes.setMinimumSize(QtCore.QSize(419, 297))
        ExpenditureTypes.setMaximumSize(QtCore.QSize(1677215, 16777215))
        self.gridLayout = QtGui.QGridLayout(ExpenditureTypes)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.expenseCategoryListView = QtGui.QTabWidget(ExpenditureTypes)
        self.expenseCategoryListView.setObjectName(_fromUtf8("expenseCategoryListView"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(0, 0, 461, 241))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout = QtGui.QFormLayout(self.frame)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_2)
        self.expenseTypeListView = QtGui.QListView(self.frame)
        self.expenseTypeListView.setAlternatingRowColors(True)
        self.expenseTypeListView.setObjectName(_fromUtf8("expenseTypeListView"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.expenseTypeListView)
        self.txtExpenseType = QtGui.QLineEdit(self.frame)
        self.txtExpenseType.setObjectName(_fromUtf8("txtExpenseType"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtExpenseType)
        self.btnExpenseSave = QtGui.QPushButton(self.frame)
        self.btnExpenseSave.setObjectName(_fromUtf8("btnExpenseSave"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.btnExpenseSave)
        self.btnExpenseDelete = QtGui.QPushButton(self.frame)
        self.btnExpenseDelete.setObjectName(_fromUtf8("btnExpenseDelete"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.btnExpenseDelete)
        self.expenseCategoryListView.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.frame_2 = QtGui.QFrame(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 461, 241))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.btnCategorySave = QtGui.QPushButton(self.frame_2)
        self.btnCategorySave.setGeometry(QtCore.QRect(271, 170, 85, 28))
        self.btnCategorySave.setObjectName(_fromUtf8("btnCategorySave"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(271, 9, 128, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btnCategoryDelete = QtGui.QPushButton(self.frame_2)
        self.btnCategoryDelete.setGeometry(QtCore.QRect(271, 204, 85, 28))
        self.btnCategoryDelete.setObjectName(_fromUtf8("btnCategoryDelete"))
        self.expenditureCategorylistView = QtGui.QListView(self.frame_2)
        self.expenditureCategorylistView.setGeometry(QtCore.QRect(9, 33, 256, 201))
        self.expenditureCategorylistView.setAlternatingRowColors(True)
        self.expenditureCategorylistView.setObjectName(_fromUtf8("expenditureCategorylistView"))
        self.txtCategory = QtGui.QLineEdit(self.frame_2)
        self.txtCategory.setGeometry(QtCore.QRect(271, 33, 163, 28))
        self.txtCategory.setObjectName(_fromUtf8("txtCategory"))
        self.label_4 = QtGui.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(9, 9, 248, 18))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.expenseCategoryListView.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.expenseCategoryListView, 0, 0, 1, 1)
        self.btnExpenditureClose = QtGui.QPushButton(ExpenditureTypes)
        self.btnExpenditureClose.setObjectName(_fromUtf8("btnExpenditureClose"))
        self.gridLayout.addWidget(self.btnExpenditureClose, 1, 0, 1, 1)

        self.retranslateUi(ExpenditureTypes)
        self.expenseCategoryListView.setCurrentIndex(0)
        QtCore.QObject.connect(self.btnExpenditureClose, QtCore.SIGNAL(_fromUtf8("clicked()")), ExpenditureTypes.mdiClose)
        QtCore.QMetaObject.connectSlotsByName(ExpenditureTypes)
        ExpenditureTypes.setTabOrder(self.expenseCategoryListView, self.btnExpenditureClose)

    def retranslateUi(self, ExpenditureTypes):
        ExpenditureTypes.setWindowTitle(QtGui.QApplication.translate("ExpenditureTypes", "Manage Expenditure Types", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ExpenditureTypes", "List of Existing Expenditure Types", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ExpenditureTypes", "Expenditure Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExpenseSave.setText(QtGui.QApplication.translate("ExpenditureTypes", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExpenseDelete.setText(QtGui.QApplication.translate("ExpenditureTypes", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.expenseCategoryListView.setTabText(self.expenseCategoryListView.indexOf(self.tab), QtGui.QApplication.translate("ExpenditureTypes", "Individual Expense Types", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCategorySave.setText(QtGui.QApplication.translate("ExpenditureTypes", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ExpenditureTypes", "Expenditure Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCategoryDelete.setText(QtGui.QApplication.translate("ExpenditureTypes", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ExpenditureTypes", "List of Existing Expenditure Types", None, QtGui.QApplication.UnicodeUTF8))
        self.expenseCategoryListView.setTabText(self.expenseCategoryListView.indexOf(self.tab_2), QtGui.QApplication.translate("ExpenditureTypes", "Main Expense Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.btnExpenditureClose.setText(QtGui.QApplication.translate("ExpenditureTypes", "Close", None, QtGui.QApplication.UnicodeUTF8))

