# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_findhouseholdresults.ui'
#
# Created: Fri Apr 22 21:39:25 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_FindHouseholdResults(object):
    def setupUi(self, FindHouseholdResults):
        FindHouseholdResults.setObjectName(_fromUtf8("FindHouseholdResults"))
        FindHouseholdResults.resize(548, 550)
        FindHouseholdResults.setMinimumSize(QtCore.QSize(548, 550))
        self.verticalLayout = QtGui.QVBoxLayout(FindHouseholdResults)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_3 = QtGui.QLabel(FindHouseholdResults)
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.lblProjectName = QtGui.QLabel(FindHouseholdResults)
        self.lblProjectName.setObjectName(_fromUtf8("lblProjectName"))
        self.verticalLayout.addWidget(self.lblProjectName)
        self.groupBox = QtGui.QGroupBox(FindHouseholdResults)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout = QtGui.QFormLayout(self.groupBox)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.SpanningRole, self.label_4)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label)
        self.txtHouseholdNo = QtGui.QLineEdit(self.groupBox)
        self.txtHouseholdNo.setObjectName(_fromUtf8("txtHouseholdNo"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtHouseholdNo)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtHouseholdName = QtGui.QLineEdit(self.groupBox)
        self.txtHouseholdName.setObjectName(_fromUtf8("txtHouseholdName"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtHouseholdName)
        self.cmdSearch = QtGui.QPushButton(self.groupBox)
        self.cmdSearch.setObjectName(_fromUtf8("cmdSearch"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.cmdSearch)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(FindHouseholdResults)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tblResults = QtGui.QTableView(self.groupBox_2)
        self.tblResults.setAlternatingRowColors(True)
        self.tblResults.setSortingEnabled(True)
        self.tblResults.setObjectName(_fromUtf8("tblResults"))
        self.horizontalLayout.addWidget(self.tblResults)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.cmdEdit = QtGui.QPushButton(self.groupBox_3)
        self.cmdEdit.setObjectName(_fromUtf8("cmdEdit"))
        self.verticalLayout_2.addWidget(self.cmdEdit)
        self.cmdDel = QtGui.QPushButton(self.groupBox_3)
        self.cmdDel.setObjectName(_fromUtf8("cmdDel"))
        self.verticalLayout_2.addWidget(self.cmdDel)
        self.cmdData = QtGui.QPushButton(self.groupBox_3)
        self.cmdData.setObjectName(_fromUtf8("cmdData"))
        self.verticalLayout_2.addWidget(self.cmdData)
        self.cmdAdd = QtGui.QPushButton(self.groupBox_3)
        self.cmdAdd.setObjectName(_fromUtf8("cmdAdd"))
        self.verticalLayout_2.addWidget(self.cmdAdd)
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.cmdClose = QtGui.QPushButton(FindHouseholdResults)
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.verticalLayout.addWidget(self.cmdClose)

        self.retranslateUi(FindHouseholdResults)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL(_fromUtf8("clicked()")), FindHouseholdResults.mdiClose)
        QtCore.QObject.connect(self.cmdSearch, QtCore.SIGNAL(_fromUtf8("clicked()")), FindHouseholdResults.getHouseholds)
        QtCore.QObject.connect(self.cmdEdit, QtCore.SIGNAL(_fromUtf8("clicked()")), FindHouseholdResults.editHousehold)
        QtCore.QObject.connect(self.cmdDel, QtCore.SIGNAL(_fromUtf8("clicked()")), FindHouseholdResults.delHouseholds)
        QtCore.QObject.connect(self.cmdData, QtCore.SIGNAL(_fromUtf8("clicked()")), FindHouseholdResults.viewHouseholdData)
        QtCore.QObject.connect(self.cmdAdd, QtCore.SIGNAL(_fromUtf8("clicked()")), FindHouseholdResults.addHousehold)
        QtCore.QMetaObject.connectSlotsByName(FindHouseholdResults)
        FindHouseholdResults.setTabOrder(self.txtHouseholdNo, self.txtHouseholdName)
        FindHouseholdResults.setTabOrder(self.txtHouseholdName, self.cmdSearch)
        FindHouseholdResults.setTabOrder(self.cmdSearch, self.tblResults)
        FindHouseholdResults.setTabOrder(self.tblResults, self.cmdEdit)
        FindHouseholdResults.setTabOrder(self.cmdEdit, self.cmdDel)
        FindHouseholdResults.setTabOrder(self.cmdDel, self.cmdData)
        FindHouseholdResults.setTabOrder(self.cmdData, self.cmdAdd)
        FindHouseholdResults.setTabOrder(self.cmdAdd, self.cmdClose)

    def retranslateUi(self, FindHouseholdResults):
        FindHouseholdResults.setWindowTitle(QtGui.QApplication.translate("FindHouseholdResults", "Household Search Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("FindHouseholdResults", "Project Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblProjectName.setText(QtGui.QApplication.translate("FindHouseholdResults", "{projectname}", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("FindHouseholdResults", "Search Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("FindHouseholdResults", "Enter Household No. or Household Name [entering nothing will list all households in the current project]", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("FindHouseholdResults", "Household No:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("FindHouseholdResults", "Household Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSearch.setText(QtGui.QApplication.translate("FindHouseholdResults", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("FindHouseholdResults", "Households", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEdit.setText(QtGui.QApplication.translate("FindHouseholdResults", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDel.setText(QtGui.QApplication.translate("FindHouseholdResults", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdData.setText(QtGui.QApplication.translate("FindHouseholdResults", "View|Edit Household Data", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAdd.setText(QtGui.QApplication.translate("FindHouseholdResults", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("FindHouseholdResults", "Close", None, QtGui.QApplication.UnicodeUTF8))

