# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_household_editmember.ui'
#
# Created: Fri Feb 04 20:56:35 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_EditHouseholdMember(object):
    def setupUi(self, EditHouseholdMember):
        EditHouseholdMember.setObjectName("EditHouseholdMember")
        EditHouseholdMember.resize(390, 424)
        self.label = QtGui.QLabel(EditHouseholdMember)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lblHouseholdName = QtGui.QLabel(EditHouseholdMember)
        self.lblHouseholdName.setGeometry(QtCore.QRect(130, 10, 251, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHouseholdName.sizePolicy().hasHeightForWidth())
        self.lblHouseholdName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblHouseholdName.setFont(font)
        self.lblHouseholdName.setObjectName("lblHouseholdName")
        self.chkHeadHousehold = QtGui.QCheckBox(EditHouseholdMember)
        self.chkHeadHousehold.setGeometry(QtCore.QRect(20, 210, 231, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chkHeadHousehold.setFont(font)
        self.chkHeadHousehold.setObjectName("chkHeadHousehold")
        self.cboSex = QtGui.QComboBox(EditHouseholdMember)
        self.cboSex.setGeometry(QtCore.QRect(130, 70, 121, 22))
        self.cboSex.setObjectName("cboSex")
        self.cboSex.addItem("")
        self.cboSex.addItem("")
        self.groupBox = QtGui.QGroupBox(EditHouseholdMember)
        self.groupBox.setGeometry(QtCore.QRect(10, 100, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cmbYearOfBirth = QtGui.QComboBox(self.groupBox)
        self.cmbYearOfBirth.setGeometry(QtCore.QRect(190, 60, 121, 22))
        self.cmbYearOfBirth.setObjectName("cmbYearOfBirth")
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtAge = QtGui.QLineEdit(self.groupBox)
        self.txtAge.setGeometry(QtCore.QRect(190, 30, 121, 20))
        self.txtAge.setObjectName("txtAge")
        self.label_4 = QtGui.QLabel(EditHouseholdMember)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.cmdCancel = QtGui.QPushButton(EditHouseholdMember)
        self.cmdCancel.setGeometry(QtCore.QRect(290, 380, 91, 31))
        self.cmdCancel.setObjectName("cmdCancel")
        self.cmdSave = QtGui.QPushButton(EditHouseholdMember)
        self.cmdSave.setGeometry(QtCore.QRect(10, 380, 91, 31))
        self.cmdSave.setObjectName("cmdSave")
        self.label_5 = QtGui.QLabel(EditHouseholdMember)
        self.label_5.setGeometry(QtCore.QRect(20, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.lblMemberID = QtGui.QLabel(EditHouseholdMember)
        self.lblMemberID.setGeometry(QtCore.QRect(130, 40, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMemberID.setFont(font)
        self.lblMemberID.setObjectName("lblMemberID")
        self.groupBox_2 = QtGui.QGroupBox(EditHouseholdMember)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 240, 371, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_7.setObjectName("label_7")
        self.txtReason = QtGui.QLineEdit(self.groupBox_2)
        self.txtReason.setGeometry(QtCore.QRect(110, 60, 251, 20))
        self.txtReason.setObjectName("txtReason")
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_8.setObjectName("label_8")
        self.txtWhere = QtGui.QLineEdit(self.groupBox_2)
        self.txtWhere.setGeometry(QtCore.QRect(110, 90, 251, 20))
        self.txtWhere.setObjectName("txtWhere")
        self.cmbMonthsAbsent = QtGui.QComboBox(self.groupBox_2)
        self.cmbMonthsAbsent.setGeometry(QtCore.QRect(110, 30, 61, 22))
        self.cmbMonthsAbsent.setObjectName("cmbMonthsAbsent")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")
        self.cmbMonthsAbsent.addItem("")

        self.retranslateUi(EditHouseholdMember)
        QtCore.QMetaObject.connectSlotsByName(EditHouseholdMember)
        EditHouseholdMember.setTabOrder(self.cboSex, self.txtAge)
        EditHouseholdMember.setTabOrder(self.txtAge, self.cmbYearOfBirth)
        EditHouseholdMember.setTabOrder(self.cmbYearOfBirth, self.chkHeadHousehold)
        EditHouseholdMember.setTabOrder(self.chkHeadHousehold, self.cmbMonthsAbsent)
        EditHouseholdMember.setTabOrder(self.cmbMonthsAbsent, self.txtReason)
        EditHouseholdMember.setTabOrder(self.txtReason, self.txtWhere)
        EditHouseholdMember.setTabOrder(self.txtWhere, self.cmdSave)
        EditHouseholdMember.setTabOrder(self.cmdSave, self.cmdCancel)

    def retranslateUi(self, EditHouseholdMember):
        EditHouseholdMember.setWindowTitle(QtGui.QApplication.translate("EditHouseholdMember", "Edit Household Member", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EditHouseholdMember", "Household Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHouseholdName.setText(QtGui.QApplication.translate("EditHouseholdMember", "{name}", None, QtGui.QApplication.UnicodeUTF8))
        self.chkHeadHousehold.setText(QtGui.QApplication.translate("EditHouseholdMember", "This member is head of household", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSex.setItemText(0, QtGui.QApplication.translate("EditHouseholdMember", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSex.setItemText(1, QtGui.QApplication.translate("EditHouseholdMember", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("EditHouseholdMember", "Household Member\'s Age or Year of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EditHouseholdMember", "Year of Birth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EditHouseholdMember", "Age of Household Member:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EditHouseholdMember", "Sex:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancel.setText(QtGui.QApplication.translate("EditHouseholdMember", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSave.setText(QtGui.QApplication.translate("EditHouseholdMember", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("EditHouseholdMember", "Member ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMemberID.setText(QtGui.QApplication.translate("EditHouseholdMember", "{memberid}", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("EditHouseholdMember", "Member Absence from Household", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EditHouseholdMember", "Month Absent:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("EditHouseholdMember", "Reason:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("EditHouseholdMember", "Where To:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(0, QtGui.QApplication.translate("EditHouseholdMember", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(1, QtGui.QApplication.translate("EditHouseholdMember", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(2, QtGui.QApplication.translate("EditHouseholdMember", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(3, QtGui.QApplication.translate("EditHouseholdMember", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(4, QtGui.QApplication.translate("EditHouseholdMember", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(5, QtGui.QApplication.translate("EditHouseholdMember", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(6, QtGui.QApplication.translate("EditHouseholdMember", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(7, QtGui.QApplication.translate("EditHouseholdMember", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(8, QtGui.QApplication.translate("EditHouseholdMember", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(9, QtGui.QApplication.translate("EditHouseholdMember", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(10, QtGui.QApplication.translate("EditHouseholdMember", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(11, QtGui.QApplication.translate("EditHouseholdMember", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(12, QtGui.QApplication.translate("EditHouseholdMember", "12", None, QtGui.QApplication.UnicodeUTF8))

