# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_household_editmember.ui'
#
# Created: Thu Apr 21 19:28:06 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_EditHouseholdMember(object):
    def setupUi(self, EditHouseholdMember):
        EditHouseholdMember.setObjectName(_fromUtf8("EditHouseholdMember"))
        EditHouseholdMember.resize(390, 427)
        self.formLayout_3 = QtGui.QFormLayout(EditHouseholdMember)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label = QtGui.QLabel(EditHouseholdMember)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lblHouseholdName = QtGui.QLabel(EditHouseholdMember)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHouseholdName.sizePolicy().hasHeightForWidth())
        self.lblHouseholdName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblHouseholdName.setFont(font)
        self.lblHouseholdName.setObjectName(_fromUtf8("lblHouseholdName"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lblHouseholdName)
        self.label_5 = QtGui.QLabel(EditHouseholdMember)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.lblMemberID = QtGui.QLabel(EditHouseholdMember)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblMemberID.setFont(font)
        self.lblMemberID.setObjectName(_fromUtf8("lblMemberID"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.lblMemberID)
        self.label_4 = QtGui.QLabel(EditHouseholdMember)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.cboSex = QtGui.QComboBox(EditHouseholdMember)
        self.cboSex.setObjectName(_fromUtf8("cboSex"))
        self.cboSex.addItem(_fromUtf8(""))
        self.cboSex.addItem(_fromUtf8(""))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.cboSex)
        self.chkHeadHousehold = QtGui.QCheckBox(EditHouseholdMember)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chkHeadHousehold.setFont(font)
        self.chkHeadHousehold.setObjectName(_fromUtf8("chkHeadHousehold"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.SpanningRole, self.chkHeadHousehold)
        self.groupBox = QtGui.QGroupBox(EditHouseholdMember)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.formLayout_2 = QtGui.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtAge = QtGui.QLineEdit(self.groupBox)
        self.txtAge.setObjectName(_fromUtf8("txtAge"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.txtAge)
        self.label_3 = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.cmbYearOfBirth = QtGui.QComboBox(self.groupBox)
        self.cmbYearOfBirth.setObjectName(_fromUtf8("cmbYearOfBirth"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbYearOfBirth)
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.SpanningRole, self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(EditHouseholdMember)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.formLayout = QtGui.QFormLayout(self.groupBox_2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.cmbMonthsAbsent = QtGui.QComboBox(self.groupBox_2)
        self.cmbMonthsAbsent.setObjectName(_fromUtf8("cmbMonthsAbsent"))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbMonthsAbsent)
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_7)
        self.txtReason = QtGui.QLineEdit(self.groupBox_2)
        self.txtReason.setObjectName(_fromUtf8("txtReason"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.txtReason)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_8)
        self.txtWhere = QtGui.QLineEdit(self.groupBox_2)
        self.txtWhere.setObjectName(_fromUtf8("txtWhere"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.txtWhere)
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.SpanningRole, self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(EditHouseholdMember)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdSave = QtGui.QPushButton(self.groupBox_3)
        self.cmdSave.setObjectName(_fromUtf8("cmdSave"))
        self.horizontalLayout.addWidget(self.cmdSave)
        self.cmdCancel = QtGui.QPushButton(self.groupBox_3)
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.horizontalLayout.addWidget(self.cmdCancel)
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.SpanningRole, self.groupBox_3)

        self.retranslateUi(EditHouseholdMember)
        QtCore.QObject.connect(self.txtAge, QtCore.SIGNAL(_fromUtf8("editingFinished()")), EditHouseholdMember.updateYearOfBirth)
        QtCore.QObject.connect(self.cmbYearOfBirth, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), EditHouseholdMember.updateAge)
        QtCore.QObject.connect(self.txtAge, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), EditHouseholdMember.updateYearOfBirth)
        QtCore.QMetaObject.connectSlotsByName(EditHouseholdMember)
        EditHouseholdMember.setTabOrder(self.cboSex, self.txtAge)
        EditHouseholdMember.setTabOrder(self.txtAge, self.cmbYearOfBirth)
        EditHouseholdMember.setTabOrder(self.cmbYearOfBirth, self.chkHeadHousehold)
        EditHouseholdMember.setTabOrder(self.chkHeadHousehold, self.cmbMonthsAbsent)
        EditHouseholdMember.setTabOrder(self.cmbMonthsAbsent, self.txtReason)
        EditHouseholdMember.setTabOrder(self.txtReason, self.txtWhere)

    def retranslateUi(self, EditHouseholdMember):
        EditHouseholdMember.setWindowTitle(QtGui.QApplication.translate("EditHouseholdMember", "Edit Household Member", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("EditHouseholdMember", "Household Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHouseholdName.setText(QtGui.QApplication.translate("EditHouseholdMember", "{name}", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("EditHouseholdMember", "Member ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.lblMemberID.setText(QtGui.QApplication.translate("EditHouseholdMember", "{memberid}", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("EditHouseholdMember", "Sex:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSex.setItemText(0, QtGui.QApplication.translate("EditHouseholdMember", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSex.setItemText(1, QtGui.QApplication.translate("EditHouseholdMember", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.chkHeadHousehold.setText(QtGui.QApplication.translate("EditHouseholdMember", "This member is head of household", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("EditHouseholdMember", "Household Member\'s Age or Year of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("EditHouseholdMember", "Age of Household Member:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("EditHouseholdMember", "Year of Birth:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("EditHouseholdMember", "Member Absence from Household", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("EditHouseholdMember", "Month Absent:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(0, QtGui.QApplication.translate("EditHouseholdMember", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(1, QtGui.QApplication.translate("EditHouseholdMember", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(2, QtGui.QApplication.translate("EditHouseholdMember", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(3, QtGui.QApplication.translate("EditHouseholdMember", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(4, QtGui.QApplication.translate("EditHouseholdMember", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(5, QtGui.QApplication.translate("EditHouseholdMember", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(6, QtGui.QApplication.translate("EditHouseholdMember", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(7, QtGui.QApplication.translate("EditHouseholdMember", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(8, QtGui.QApplication.translate("EditHouseholdMember", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(9, QtGui.QApplication.translate("EditHouseholdMember", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(10, QtGui.QApplication.translate("EditHouseholdMember", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(11, QtGui.QApplication.translate("EditHouseholdMember", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(12, QtGui.QApplication.translate("EditHouseholdMember", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("EditHouseholdMember", "Reason:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("EditHouseholdMember", "Where To:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSave.setText(QtGui.QApplication.translate("EditHouseholdMember", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancel.setText(QtGui.QApplication.translate("EditHouseholdMember", "Cancel", None, QtGui.QApplication.UnicodeUTF8))

