# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_household_details.ui'
#
# Created: Fri Mar 05 11:18:37 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_HouseholdDetails(object):
    def setupUi(self, HouseholdDetails):
        HouseholdDetails.setObjectName("HouseholdDetails")
        HouseholdDetails.resize(797, 620)
        self.tabHouseHold = QtGui.QTabWidget(HouseholdDetails)
        self.tabHouseHold.setGeometry(QtCore.QRect(10, 40, 781, 531))
        self.tabHouseHold.setObjectName("tabHouseHold")
        self.tabHouseHoldMembers = QtGui.QWidget()
        self.tabHouseHoldMembers.setObjectName("tabHouseHoldMembers")
        self.tableView = QtGui.QTableView(self.tabHouseHoldMembers)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tableView.setObjectName("tableView")
        self.cmdAddMember = QtGui.QPushButton(self.tabHouseHoldMembers)
        self.cmdAddMember.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdAddMember.setObjectName("cmdAddMember")
        self.cmdEditMember = QtGui.QPushButton(self.tabHouseHoldMembers)
        self.cmdEditMember.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.cmdEditMember.setObjectName("cmdEditMember")
        self.cmdDelMember = QtGui.QPushButton(self.tabHouseHoldMembers)
        self.cmdDelMember.setGeometry(QtCore.QRect(210, 470, 91, 31))
        self.cmdDelMember.setObjectName("cmdDelMember")
        self.tabHouseHold.addTab(self.tabHouseHoldMembers, "")
        self.tabHouseholdIncome = QtGui.QWidget()
        self.tabHouseholdIncome.setObjectName("tabHouseholdIncome")
        self.tableView_2 = QtGui.QTableView(self.tabHouseholdIncome)
        self.tableView_2.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tableView_2.setObjectName("tableView_2")
        self.cmdAddIncome = QtGui.QPushButton(self.tabHouseholdIncome)
        self.cmdAddIncome.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdAddIncome.setObjectName("cmdAddIncome")
        self.cmdEditIncome = QtGui.QPushButton(self.tabHouseholdIncome)
        self.cmdEditIncome.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.cmdEditIncome.setObjectName("cmdEditIncome")
        self.pushButton_6 = QtGui.QPushButton(self.tabHouseholdIncome)
        self.pushButton_6.setGeometry(QtCore.QRect(210, 470, 91, 31))
        self.pushButton_6.setObjectName("pushButton_6")
        self.tabHouseHold.addTab(self.tabHouseholdIncome, "")
        self.tabHouseholdAssets = QtGui.QWidget()
        self.tabHouseholdAssets.setObjectName("tabHouseholdAssets")
        self.tableView_3 = QtGui.QTableView(self.tabHouseholdAssets)
        self.tableView_3.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tableView_3.setObjectName("tableView_3")
        self.cmdAddAsset = QtGui.QPushButton(self.tabHouseholdAssets)
        self.cmdAddAsset.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdAddAsset.setObjectName("cmdAddAsset")
        self.cmdEditAsset = QtGui.QPushButton(self.tabHouseholdAssets)
        self.cmdEditAsset.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.cmdEditAsset.setObjectName("cmdEditAsset")
        self.cmdDelAsset = QtGui.QPushButton(self.tabHouseholdAssets)
        self.cmdDelAsset.setGeometry(QtCore.QRect(210, 470, 91, 31))
        self.cmdDelAsset.setObjectName("cmdDelAsset")
        self.tabHouseHold.addTab(self.tabHouseholdAssets, "")
        self.tabHouseholdExpenditure = QtGui.QWidget()
        self.tabHouseholdExpenditure.setObjectName("tabHouseholdExpenditure")
        self.tableView_4 = QtGui.QTableView(self.tabHouseholdExpenditure)
        self.tableView_4.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tableView_4.setObjectName("tableView_4")
        self.cmdAddExpenditure = QtGui.QPushButton(self.tabHouseholdExpenditure)
        self.cmdAddExpenditure.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdAddExpenditure.setObjectName("cmdAddExpenditure")
        self.cmdEditExpenditure = QtGui.QPushButton(self.tabHouseholdExpenditure)
        self.cmdEditExpenditure.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.cmdEditExpenditure.setObjectName("cmdEditExpenditure")
        self.cmdDelExpenditure = QtGui.QPushButton(self.tabHouseholdExpenditure)
        self.cmdDelExpenditure.setGeometry(QtCore.QRect(210, 470, 91, 31))
        self.cmdDelExpenditure.setObjectName("cmdDelExpenditure")
        self.tabHouseHold.addTab(self.tabHouseholdExpenditure, "")
        self.tabHouseholdCharacteristics = QtGui.QWidget()
        self.tabHouseholdCharacteristics.setObjectName("tabHouseholdCharacteristics")
        self.tableView_5 = QtGui.QTableView(self.tabHouseholdCharacteristics)
        self.tableView_5.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tableView_5.setObjectName("tableView_5")
        self.cmdEditCharacteristic = QtGui.QPushButton(self.tabHouseholdCharacteristics)
        self.cmdEditCharacteristic.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdEditCharacteristic.setObjectName("cmdEditCharacteristic")
        self.tabHouseHold.addTab(self.tabHouseholdCharacteristics, "")
        self.cmdClose = QtGui.QPushButton(HouseholdDetails)
        self.cmdClose.setGeometry(QtCore.QRect(694, 580, 91, 31))
        self.cmdClose.setObjectName("cmdClose")
        self.cboHouseholdNumber = QtGui.QComboBox(HouseholdDetails)
        self.cboHouseholdNumber.setGeometry(QtCore.QRect(140, 10, 221, 22))
        self.cboHouseholdNumber.setObjectName("cboHouseholdNumber")
        self.label = QtGui.QLabel(HouseholdDetails)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label.setObjectName("label")

        self.retranslateUi(HouseholdDetails)
        self.tabHouseHold.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(HouseholdDetails)

    def retranslateUi(self, HouseholdDetails):
        HouseholdDetails.setWindowTitle(QtGui.QApplication.translate("HouseholdDetails", "Household Details", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddMember.setText(QtGui.QApplication.translate("HouseholdDetails", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditMember.setText(QtGui.QApplication.translate("HouseholdDetails", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelMember.setText(QtGui.QApplication.translate("HouseholdDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseHoldMembers), QtGui.QApplication.translate("HouseholdDetails", "Members", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddIncome.setText(QtGui.QApplication.translate("HouseholdDetails", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditIncome.setText(QtGui.QApplication.translate("HouseholdDetails", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_6.setText(QtGui.QApplication.translate("HouseholdDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdIncome), QtGui.QApplication.translate("HouseholdDetails", "Income", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddAsset.setText(QtGui.QApplication.translate("HouseholdDetails", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditAsset.setText(QtGui.QApplication.translate("HouseholdDetails", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelAsset.setText(QtGui.QApplication.translate("HouseholdDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdAssets), QtGui.QApplication.translate("HouseholdDetails", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddExpenditure.setText(QtGui.QApplication.translate("HouseholdDetails", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditExpenditure.setText(QtGui.QApplication.translate("HouseholdDetails", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelExpenditure.setText(QtGui.QApplication.translate("HouseholdDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdExpenditure), QtGui.QApplication.translate("HouseholdDetails", "Expenditure", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditCharacteristic.setText(QtGui.QApplication.translate("HouseholdDetails", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdCharacteristics), QtGui.QApplication.translate("HouseholdDetails", "Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdDetails", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdDetails", "Household Number:", None, QtGui.QApplication.UnicodeUTF8))

