# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_household_addmember.ui'
#
# Created: Tue Apr 19 03:45:24 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_AddHouseholdMember(object):
    def setupUi(self, AddHouseholdMember):
        AddHouseholdMember.setObjectName(_fromUtf8("AddHouseholdMember"))
        AddHouseholdMember.setWindowModality(QtCore.Qt.NonModal)
        AddHouseholdMember.resize(392, 393)
        self.chkHeadHousehold = QtGui.QCheckBox(AddHouseholdMember)
        self.chkHeadHousehold.setGeometry(QtCore.QRect(20, 180, 231, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.chkHeadHousehold.setFont(font)
        self.chkHeadHousehold.setObjectName(_fromUtf8("chkHeadHousehold"))
        self.cmdSave = QtGui.QPushButton(AddHouseholdMember)
        self.cmdSave.setGeometry(QtCore.QRect(10, 350, 91, 31))
        self.cmdSave.setObjectName(_fromUtf8("cmdSave"))
        self.lblHouseholdName = QtGui.QLabel(AddHouseholdMember)
        self.lblHouseholdName.setGeometry(QtCore.QRect(130, 10, 251, 16))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblHouseholdName.sizePolicy().hasHeightForWidth())
        self.lblHouseholdName.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblHouseholdName.setFont(font)
        self.lblHouseholdName.setObjectName(_fromUtf8("lblHouseholdName"))
        self.label = QtGui.QLabel(AddHouseholdMember)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.cboSex = QtGui.QComboBox(AddHouseholdMember)
        self.cboSex.setGeometry(QtCore.QRect(200, 40, 121, 22))
        self.cboSex.setObjectName(_fromUtf8("cboSex"))
        self.cboSex.addItem(_fromUtf8(""))
        self.cboSex.addItem(_fromUtf8(""))
        self.label_4 = QtGui.QLabel(AddHouseholdMember)
        self.label_4.setGeometry(QtCore.QRect(20, 40, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.cmdCancel = QtGui.QPushButton(AddHouseholdMember)
        self.cmdCancel.setGeometry(QtCore.QRect(290, 350, 91, 31))
        self.cmdCancel.setObjectName(_fromUtf8("cmdCancel"))
        self.groupBox = QtGui.QGroupBox(AddHouseholdMember)
        self.groupBox.setGeometry(QtCore.QRect(10, 70, 371, 101))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(20, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmbYearOfBirth = QtGui.QComboBox(self.groupBox)
        self.cmbYearOfBirth.setGeometry(QtCore.QRect(190, 60, 121, 22))
        self.cmbYearOfBirth.setObjectName(_fromUtf8("cmbYearOfBirth"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(20, 30, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.txtAge = QtGui.QLineEdit(self.groupBox)
        self.txtAge.setGeometry(QtCore.QRect(190, 30, 121, 20))
        self.txtAge.setObjectName(_fromUtf8("txtAge"))
        self.groupBox_2 = QtGui.QGroupBox(AddHouseholdMember)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 209, 371, 131))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.label_5 = QtGui.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 60, 101, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.txtReason = QtGui.QLineEdit(self.groupBox_2)
        self.txtReason.setGeometry(QtCore.QRect(110, 60, 251, 20))
        self.txtReason.setObjectName(_fromUtf8("txtReason"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.txtWhere = QtGui.QLineEdit(self.groupBox_2)
        self.txtWhere.setGeometry(QtCore.QRect(110, 90, 251, 20))
        self.txtWhere.setObjectName(_fromUtf8("txtWhere"))
        self.cmbMonthsAbsent = QtGui.QComboBox(self.groupBox_2)
        self.cmbMonthsAbsent.setGeometry(QtCore.QRect(110, 30, 61, 22))
        self.cmbMonthsAbsent.setObjectName(_fromUtf8("cmbMonthsAbsent"))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))
        self.cmbMonthsAbsent.addItem(_fromUtf8(""))

        self.retranslateUi(AddHouseholdMember)
        QtCore.QObject.connect(self.cmdCancel, QtCore.SIGNAL(_fromUtf8("clicked()")), AddHouseholdMember.mdiClose)
        QtCore.QObject.connect(self.cmdSave, QtCore.SIGNAL(_fromUtf8("clicked()")), AddHouseholdMember.saveMember)
        QtCore.QObject.connect(self.cmbYearOfBirth, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), AddHouseholdMember.updateYearOfBirth)
        QtCore.QObject.connect(self.txtAge, QtCore.SIGNAL(_fromUtf8("editingFinished()")), AddHouseholdMember.updateYearOfBirth)
        QtCore.QMetaObject.connectSlotsByName(AddHouseholdMember)
        AddHouseholdMember.setTabOrder(self.cboSex, self.txtAge)
        AddHouseholdMember.setTabOrder(self.txtAge, self.cmbYearOfBirth)
        AddHouseholdMember.setTabOrder(self.cmbYearOfBirth, self.chkHeadHousehold)
        AddHouseholdMember.setTabOrder(self.chkHeadHousehold, self.cmbMonthsAbsent)
        AddHouseholdMember.setTabOrder(self.cmbMonthsAbsent, self.txtReason)
        AddHouseholdMember.setTabOrder(self.txtReason, self.txtWhere)
        AddHouseholdMember.setTabOrder(self.txtWhere, self.cmdSave)
        AddHouseholdMember.setTabOrder(self.cmdSave, self.cmdCancel)

    def retranslateUi(self, AddHouseholdMember):
        AddHouseholdMember.setWindowTitle(QtGui.QApplication.translate("AddHouseholdMember", "Add Household Member", None, QtGui.QApplication.UnicodeUTF8))
        self.chkHeadHousehold.setText(QtGui.QApplication.translate("AddHouseholdMember", "This member is head of household", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSave.setText(QtGui.QApplication.translate("AddHouseholdMember", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.lblHouseholdName.setText(QtGui.QApplication.translate("AddHouseholdMember", "{name}", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("AddHouseholdMember", "Household Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSex.setItemText(0, QtGui.QApplication.translate("AddHouseholdMember", "Male", None, QtGui.QApplication.UnicodeUTF8))
        self.cboSex.setItemText(1, QtGui.QApplication.translate("AddHouseholdMember", "Female", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("AddHouseholdMember", "Sex:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdCancel.setText(QtGui.QApplication.translate("AddHouseholdMember", "Cancel", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("AddHouseholdMember", "Household Member\'s Age or Year of Birth", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("AddHouseholdMember", "Year of Birth:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("AddHouseholdMember", "Age of Household Member:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("AddHouseholdMember", "Member Absence from Household", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("AddHouseholdMember", "Month Absent:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("AddHouseholdMember", "Reason:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("AddHouseholdMember", "Where To:", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(0, QtGui.QApplication.translate("AddHouseholdMember", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(1, QtGui.QApplication.translate("AddHouseholdMember", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(2, QtGui.QApplication.translate("AddHouseholdMember", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(3, QtGui.QApplication.translate("AddHouseholdMember", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(4, QtGui.QApplication.translate("AddHouseholdMember", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(5, QtGui.QApplication.translate("AddHouseholdMember", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(6, QtGui.QApplication.translate("AddHouseholdMember", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(7, QtGui.QApplication.translate("AddHouseholdMember", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(8, QtGui.QApplication.translate("AddHouseholdMember", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(9, QtGui.QApplication.translate("AddHouseholdMember", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(10, QtGui.QApplication.translate("AddHouseholdMember", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(11, QtGui.QApplication.translate("AddHouseholdMember", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbMonthsAbsent.setItemText(12, QtGui.QApplication.translate("AddHouseholdMember", "12", None, QtGui.QApplication.UnicodeUTF8))

