# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_household_data.ui'
#
# Created: Sun Oct 17 08:29:21 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_HouseholdData(object):
    def setupUi(self, HouseholdData):
        HouseholdData.setObjectName("HouseholdData")
        HouseholdData.resize(797, 620)
        HouseholdData.setMinimumSize(QtCore.QSize(797, 620))
        self.tabHouseHold = QtGui.QTabWidget(HouseholdData)
        self.tabHouseHold.setGeometry(QtCore.QRect(10, 40, 781, 531))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabHouseHold.setFont(font)
        self.tabHouseHold.setObjectName("tabHouseHold")
        self.tabHouseHoldMembers = QtGui.QWidget()
        self.tabHouseHoldMembers.setObjectName("tabHouseHoldMembers")
        self.tblMembers = QtGui.QTableView(self.tabHouseHoldMembers)
        self.tblMembers.setGeometry(QtCore.QRect(10, 30, 371, 431))
        self.tblMembers.setObjectName("tblMembers")
        self.cmdAddMember = QtGui.QPushButton(self.tabHouseHoldMembers)
        self.cmdAddMember.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdAddMember.setObjectName("cmdAddMember")
        self.cmdEditMember = QtGui.QPushButton(self.tabHouseHoldMembers)
        self.cmdEditMember.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.cmdEditMember.setObjectName("cmdEditMember")
        self.cmdDelMember = QtGui.QPushButton(self.tabHouseHoldMembers)
        self.cmdDelMember.setGeometry(QtCore.QRect(210, 470, 91, 31))
        self.cmdDelMember.setObjectName("cmdDelMember")
        self.tblPersonalCharacteristics = QtGui.QTableView(self.tabHouseHoldMembers)
        self.tblPersonalCharacteristics.setGeometry(QtCore.QRect(390, 30, 371, 431))
        self.tblPersonalCharacteristics.setObjectName("tblPersonalCharacteristics")
        self.cmdEditPersonalCharacteristic = QtGui.QPushButton(self.tabHouseHoldMembers)
        self.cmdEditPersonalCharacteristic.setGeometry(QtCore.QRect(390, 470, 141, 31))
        self.cmdEditPersonalCharacteristic.setObjectName("cmdEditPersonalCharacteristic")
        self.label_8 = QtGui.QLabel(self.tabHouseHoldMembers)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_8.setObjectName("label_8")
        self.lblPersonalCharacteristicsHeader = QtGui.QLabel(self.tabHouseHoldMembers)
        self.lblPersonalCharacteristicsHeader.setGeometry(QtCore.QRect(400, 10, 231, 16))
        self.lblPersonalCharacteristicsHeader.setObjectName("lblPersonalCharacteristicsHeader")
        self.tabHouseHold.addTab(self.tabHouseHoldMembers, "")
        self.tabHouseholdAssets = QtGui.QWidget()
        self.tabHouseholdAssets.setObjectName("tabHouseholdAssets")
        self.tblAssets = QtGui.QTableView(self.tabHouseholdAssets)
        self.tblAssets.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tblAssets.setObjectName("tblAssets")
        self.cmdAddAsset = QtGui.QPushButton(self.tabHouseholdAssets)
        self.cmdAddAsset.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdAddAsset.setObjectName("cmdAddAsset")
        self.cmdEditAsset = QtGui.QPushButton(self.tabHouseholdAssets)
        self.cmdEditAsset.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.cmdEditAsset.setObjectName("cmdEditAsset")
        self.cmdDelAsset = QtGui.QPushButton(self.tabHouseholdAssets)
        self.cmdDelAsset.setGeometry(QtCore.QRect(210, 470, 91, 31))
        self.cmdDelAsset.setObjectName("cmdDelAsset")
        self.tabHouseHold.addTab(self.tabHouseholdAssets, "")
        self.tabHouseholdIncome = QtGui.QWidget()
        self.tabHouseholdIncome.setObjectName("tabHouseholdIncome")
        self.tabWidget = QtGui.QTabWidget(self.tabHouseholdIncome)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 751, 491))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.West)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.cmdAddCrop = QtGui.QPushButton(self.tab)
        self.cmdAddCrop.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.cmdAddCrop.setObjectName("cmdAddCrop")
        self.cmdEditCrop = QtGui.QPushButton(self.tab)
        self.cmdEditCrop.setGeometry(QtCore.QRect(120, 450, 91, 31))
        self.cmdEditCrop.setObjectName("cmdEditCrop")
        self.cmdDelCrop = QtGui.QPushButton(self.tab)
        self.cmdDelCrop.setGeometry(QtCore.QRect(220, 450, 91, 31))
        self.cmdDelCrop.setObjectName("cmdDelCrop")
        self.tblCropIncome = QtGui.QTableView(self.tab)
        self.tblCropIncome.setGeometry(QtCore.QRect(10, 40, 701, 401))
        self.tblCropIncome.setObjectName("tblCropIncome")
        self.label_2 = QtGui.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(20, 10, 161, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tblLivestockIncome = QtGui.QTableView(self.tab_2)
        self.tblLivestockIncome.setGeometry(QtCore.QRect(10, 40, 701, 401))
        self.tblLivestockIncome.setObjectName("tblLivestockIncome")
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(20, 10, 121, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.cmdEditLivestock = QtGui.QPushButton(self.tab_2)
        self.cmdEditLivestock.setGeometry(QtCore.QRect(120, 450, 91, 31))
        self.cmdEditLivestock.setObjectName("cmdEditLivestock")
        self.cmdDelLivestock = QtGui.QPushButton(self.tab_2)
        self.cmdDelLivestock.setGeometry(QtCore.QRect(220, 450, 91, 31))
        self.cmdDelLivestock.setObjectName("cmdDelLivestock")
        self.cmdAddLivestock = QtGui.QPushButton(self.tab_2)
        self.cmdAddLivestock.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.cmdAddLivestock.setObjectName("cmdAddLivestock")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(20, 10, 121, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.tblEmploymentIncome = QtGui.QTableView(self.tab_3)
        self.tblEmploymentIncome.setGeometry(QtCore.QRect(10, 40, 701, 401))
        self.tblEmploymentIncome.setObjectName("tblEmploymentIncome")
        self.cmdEditEmployment = QtGui.QPushButton(self.tab_3)
        self.cmdEditEmployment.setGeometry(QtCore.QRect(120, 450, 91, 31))
        self.cmdEditEmployment.setObjectName("cmdEditEmployment")
        self.cmdDelEmployment = QtGui.QPushButton(self.tab_3)
        self.cmdDelEmployment.setGeometry(QtCore.QRect(220, 450, 91, 31))
        self.cmdDelEmployment.setObjectName("cmdDelEmployment")
        self.cmdAddEmployment = QtGui.QPushButton(self.tab_3)
        self.cmdAddEmployment.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.cmdAddEmployment.setObjectName("cmdAddEmployment")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setGeometry(QtCore.QRect(20, 10, 151, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tblWildfoodsIncome = QtGui.QTableView(self.tab_4)
        self.tblWildfoodsIncome.setGeometry(QtCore.QRect(10, 40, 701, 401))
        self.tblWildfoodsIncome.setObjectName("tblWildfoodsIncome")
        self.cmdEditWildfoods = QtGui.QPushButton(self.tab_4)
        self.cmdEditWildfoods.setGeometry(QtCore.QRect(120, 450, 91, 31))
        self.cmdEditWildfoods.setObjectName("cmdEditWildfoods")
        self.cmdDelWildfoods = QtGui.QPushButton(self.tab_4)
        self.cmdDelWildfoods.setGeometry(QtCore.QRect(220, 450, 91, 31))
        self.cmdDelWildfoods.setObjectName("cmdDelWildfoods")
        self.cmdAddWildfoods = QtGui.QPushButton(self.tab_4)
        self.cmdAddWildfoods.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.cmdAddWildfoods.setObjectName("cmdAddWildfoods")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 121, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tblGiftsIncome = QtGui.QTableView(self.tab_5)
        self.tblGiftsIncome.setGeometry(QtCore.QRect(10, 40, 701, 401))
        self.tblGiftsIncome.setObjectName("tblGiftsIncome")
        self.cmdEditGifts = QtGui.QPushButton(self.tab_5)
        self.cmdEditGifts.setGeometry(QtCore.QRect(120, 450, 91, 31))
        self.cmdEditGifts.setObjectName("cmdEditGifts")
        self.cmdDelGifts = QtGui.QPushButton(self.tab_5)
        self.cmdDelGifts.setGeometry(QtCore.QRect(220, 450, 91, 31))
        self.cmdDelGifts.setObjectName("cmdDelGifts")
        self.cmdAddGifts = QtGui.QPushButton(self.tab_5)
        self.cmdAddGifts.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.cmdAddGifts.setObjectName("cmdAddGifts")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtGui.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.label_7 = QtGui.QLabel(self.tab_6)
        self.label_7.setGeometry(QtCore.QRect(20, 10, 221, 21))
        font = QtGui.QFont()
        font.setWeight(75)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.tblTransferIncome = QtGui.QTableView(self.tab_6)
        self.tblTransferIncome.setGeometry(QtCore.QRect(10, 40, 701, 401))
        self.tblTransferIncome.setObjectName("tblTransferIncome")
        self.cmdEditTransfer = QtGui.QPushButton(self.tab_6)
        self.cmdEditTransfer.setGeometry(QtCore.QRect(120, 450, 91, 31))
        self.cmdEditTransfer.setObjectName("cmdEditTransfer")
        self.cmdDelTransfer = QtGui.QPushButton(self.tab_6)
        self.cmdDelTransfer.setGeometry(QtCore.QRect(220, 450, 91, 31))
        self.cmdDelTransfer.setObjectName("cmdDelTransfer")
        self.cmdAddTransfer = QtGui.QPushButton(self.tab_6)
        self.cmdAddTransfer.setGeometry(QtCore.QRect(20, 450, 91, 31))
        self.cmdAddTransfer.setObjectName("cmdAddTransfer")
        self.tabWidget.addTab(self.tab_6, "")
        self.tabHouseHold.addTab(self.tabHouseholdIncome, "")
        self.tabHouseholdExpenditure = QtGui.QWidget()
        self.tabHouseholdExpenditure.setObjectName("tabHouseholdExpenditure")
        self.tblExpenditure = QtGui.QTableView(self.tabHouseholdExpenditure)
        self.tblExpenditure.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tblExpenditure.setObjectName("tblExpenditure")
        self.cmdAddExpenditure = QtGui.QPushButton(self.tabHouseholdExpenditure)
        self.cmdAddExpenditure.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdAddExpenditure.setObjectName("cmdAddExpenditure")
        self.cmdEditExpenditure = QtGui.QPushButton(self.tabHouseholdExpenditure)
        self.cmdEditExpenditure.setGeometry(QtCore.QRect(110, 470, 91, 31))
        self.cmdEditExpenditure.setObjectName("cmdEditExpenditure")
        self.cmdDelExpenditure = QtGui.QPushButton(self.tabHouseholdExpenditure)
        self.cmdDelExpenditure.setGeometry(QtCore.QRect(210, 470, 91, 31))
        self.cmdDelExpenditure.setObjectName("cmdDelExpenditure")
        self.tabHouseHold.addTab(self.tabHouseholdExpenditure, "")
        self.tabHouseholdCharacteristics = QtGui.QWidget()
        self.tabHouseholdCharacteristics.setObjectName("tabHouseholdCharacteristics")
        self.tblCharacteristics = QtGui.QTableView(self.tabHouseholdCharacteristics)
        self.tblCharacteristics.setGeometry(QtCore.QRect(10, 10, 751, 451))
        self.tblCharacteristics.setObjectName("tblCharacteristics")
        self.cmdEditCharacteristic = QtGui.QPushButton(self.tabHouseholdCharacteristics)
        self.cmdEditCharacteristic.setGeometry(QtCore.QRect(10, 470, 91, 31))
        self.cmdEditCharacteristic.setObjectName("cmdEditCharacteristic")
        self.tabHouseHold.addTab(self.tabHouseholdCharacteristics, "")
        self.cmdClose = QtGui.QPushButton(HouseholdData)
        self.cmdClose.setGeometry(QtCore.QRect(694, 580, 91, 31))
        self.cmdClose.setObjectName("cmdClose")
        self.cboHouseholdNumber = QtGui.QComboBox(HouseholdData)
        self.cboHouseholdNumber.setGeometry(QtCore.QRect(140, 10, 221, 22))
        self.cboHouseholdNumber.setObjectName("cboHouseholdNumber")
        self.label = QtGui.QLabel(HouseholdData)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label.setObjectName("label")

        self.retranslateUi(HouseholdData)
        self.tabHouseHold.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HouseholdData)

    def retranslateUi(self, HouseholdData):
        HouseholdData.setWindowTitle(QtGui.QApplication.translate("HouseholdData", "Household Data", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddMember.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditMember.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelMember.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditPersonalCharacteristic.setText(QtGui.QApplication.translate("HouseholdData", "Edit Characteristic", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("HouseholdData", "Household Members", None, QtGui.QApplication.UnicodeUTF8))
        self.lblPersonalCharacteristicsHeader.setText(QtGui.QApplication.translate("HouseholdData", "Personal Characteristics:", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseHoldMembers), QtGui.QApplication.translate("HouseholdData", "Members", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddAsset.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditAsset.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelAsset.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdAssets), QtGui.QApplication.translate("HouseholdData", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddCrop.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditCrop.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelCrop.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdData", "Crops", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("HouseholdData", "Crops", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("HouseholdData", "Livestock", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditLivestock.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelLivestock.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddLivestock.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("HouseholdData", "Livestock", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HouseholdData", "Employment", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditEmployment.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelEmployment.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddEmployment.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("HouseholdData", "Employment", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("HouseholdData", "Wildfoods and Hunting", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditWildfoods.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelWildfoods.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddWildfoods.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("HouseholdData", "Wildfoods", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("HouseholdData", "Transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditGifts.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelGifts.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddGifts.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("HouseholdData", "Transfers", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("HouseholdData", "Transfers from Organisations", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditTransfer.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelTransfer.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddTransfer.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QtGui.QApplication.translate("HouseholdData", "Transfers From Orgs", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdIncome), QtGui.QApplication.translate("HouseholdData", "Income", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdAddExpenditure.setText(QtGui.QApplication.translate("HouseholdData", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditExpenditure.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdDelExpenditure.setText(QtGui.QApplication.translate("HouseholdData", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdExpenditure), QtGui.QApplication.translate("HouseholdData", "Expenditure", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdEditCharacteristic.setText(QtGui.QApplication.translate("HouseholdData", "Edit", None, QtGui.QApplication.UnicodeUTF8))
        self.tabHouseHold.setTabText(self.tabHouseHold.indexOf(self.tabHouseholdCharacteristics), QtGui.QApplication.translate("HouseholdData", "Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdData", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdData", "Household Name:", None, QtGui.QApplication.UnicodeUTF8))

