# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_manageassets.ui'
#
# Created: Wed Jun 02 16:50:08 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_ManageAssetDetails(object):
    def setupUi(self, ManageAssetDetails):
        ManageAssetDetails.setObjectName("ManageAssetDetails")
        ManageAssetDetails.resize(572, 380)
        ManageAssetDetails.setMinimumSize(QtCore.QSize(572, 380))
        self.tabWidget = QtGui.QTabWidget(ManageAssetDetails)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 571, 341))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setObjectName("tabWidget")
        self.tabCashSavings = QtGui.QWidget()
        self.tabCashSavings.setObjectName("tabCashSavings")
        self.label_23 = QtGui.QLabel(self.tabCashSavings)
        self.label_23.setGeometry(QtCore.QRect(260, 60, 121, 18))
        self.label_23.setObjectName("label_23")
        self.btnCashDelete = QtGui.QPushButton(self.tabCashSavings)
        self.btnCashDelete.setGeometry(QtCore.QRect(480, 150, 80, 28))
        self.btnCashDelete.setObjectName("btnCashDelete")
        self.txtSavingCategories = QtGui.QLineEdit(self.tabCashSavings)
        self.txtSavingCategories.setGeometry(QtCore.QRect(372, 60, 181, 28))
        self.txtSavingCategories.setObjectName("txtSavingCategories")
        self.label_25 = QtGui.QLabel(self.tabCashSavings)
        self.label_25.setGeometry(QtCore.QRect(290, 10, 241, 18))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtGui.QLabel(self.tabCashSavings)
        self.label_26.setGeometry(QtCore.QRect(0, 10, 221, 18))
        self.label_26.setObjectName("label_26")
        self.btnCashSave = QtGui.QPushButton(self.tabCashSavings)
        self.btnCashSave.setGeometry(QtCore.QRect(370, 150, 80, 28))
        self.btnCashSave.setObjectName("btnCashSave")
        self.savingsListView = QtGui.QListView(self.tabCashSavings)
        self.savingsListView.setGeometry(QtCore.QRect(5, 60, 241, 201))
        self.savingsListView.setObjectName("savingsListView")
        self.tabWidget.addTab(self.tabCashSavings, "")
        self.tabFoodStock = QtGui.QWidget()
        self.tabFoodStock.setObjectName("tabFoodStock")
        self.txtFoodStockType = QtGui.QLineEdit(self.tabFoodStock)
        self.txtFoodStockType.setGeometry(QtCore.QRect(352, 60, 201, 28))
        self.txtFoodStockType.setObjectName("txtFoodStockType")
        self.txtEnergyValue = QtGui.QLineEdit(self.tabFoodStock)
        self.txtEnergyValue.setGeometry(QtCore.QRect(350, 110, 201, 28))
        self.txtEnergyValue.setObjectName("txtEnergyValue")
        self.btnFoodStockSave = QtGui.QPushButton(self.tabFoodStock)
        self.btnFoodStockSave.setGeometry(QtCore.QRect(350, 240, 80, 28))
        self.btnFoodStockSave.setObjectName("btnFoodStockSave")
        self.btnFoodStockDelete = QtGui.QPushButton(self.tabFoodStock)
        self.btnFoodStockDelete.setGeometry(QtCore.QRect(460, 240, 80, 28))
        self.btnFoodStockDelete.setObjectName("btnFoodStockDelete")
        self.label_3 = QtGui.QLabel(self.tabFoodStock)
        self.label_3.setGeometry(QtCore.QRect(260, 60, 54, 18))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtGui.QLabel(self.tabFoodStock)
        self.label_5.setGeometry(QtCore.QRect(260, 120, 54, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(self.tabFoodStock)
        self.label_6.setGeometry(QtCore.QRect(0, 10, 221, 18))
        self.label_6.setObjectName("label_6")
        self.label_16 = QtGui.QLabel(self.tabFoodStock)
        self.label_16.setGeometry(QtCore.QRect(290, 10, 241, 18))
        self.label_16.setObjectName("label_16")
        self.txtMeasuringUnit = QtGui.QLineEdit(self.tabFoodStock)
        self.txtMeasuringUnit.setGeometry(QtCore.QRect(350, 160, 201, 31))
        self.txtMeasuringUnit.setObjectName("txtMeasuringUnit")
        self.label_4 = QtGui.QLabel(self.tabFoodStock)
        self.label_4.setGeometry(QtCore.QRect(260, 170, 81, 16))
        self.label_4.setObjectName("label_4")
        self.foodListView = QtGui.QListView(self.tabFoodStock)
        self.foodListView.setGeometry(QtCore.QRect(10, 50, 241, 201))
        self.foodListView.setObjectName("foodListView")
        self.tabWidget.addTab(self.tabFoodStock, "")
        self.tabLand = QtGui.QWidget()
        self.tabLand.setObjectName("tabLand")
        self.txtLandType = QtGui.QLineEdit(self.tabLand)
        self.txtLandType.setGeometry(QtCore.QRect(352, 60, 201, 28))
        self.txtLandType.setObjectName("txtLandType")
        self.btnLandSave = QtGui.QPushButton(self.tabLand)
        self.btnLandSave.setGeometry(QtCore.QRect(350, 240, 80, 28))
        self.btnLandSave.setObjectName("btnLandSave")
        self.label_7 = QtGui.QLabel(self.tabLand)
        self.label_7.setGeometry(QtCore.QRect(260, 60, 54, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtGui.QLabel(self.tabLand)
        self.label_8.setGeometry(QtCore.QRect(260, 120, 91, 18))
        self.label_8.setObjectName("label_8")
        self.txtLandMeasuringUnit = QtGui.QLineEdit(self.tabLand)
        self.txtLandMeasuringUnit.setGeometry(QtCore.QRect(350, 110, 201, 28))
        self.txtLandMeasuringUnit.setObjectName("txtLandMeasuringUnit")
        self.label_17 = QtGui.QLabel(self.tabLand)
        self.label_17.setGeometry(QtCore.QRect(290, 10, 241, 18))
        self.label_17.setObjectName("label_17")
        self.btnLandDelete = QtGui.QPushButton(self.tabLand)
        self.btnLandDelete.setGeometry(QtCore.QRect(460, 240, 80, 28))
        self.btnLandDelete.setObjectName("btnLandDelete")
        self.label_18 = QtGui.QLabel(self.tabLand)
        self.label_18.setGeometry(QtCore.QRect(0, 10, 221, 18))
        self.label_18.setObjectName("label_18")
        self.landListView = QtGui.QListView(self.tabLand)
        self.landListView.setGeometry(QtCore.QRect(5, 50, 241, 201))
        self.landListView.setObjectName("landListView")
        self.tabWidget.addTab(self.tabLand, "")
        self.tabTrees = QtGui.QWidget()
        self.tabTrees.setObjectName("tabTrees")
        self.label_10 = QtGui.QLabel(self.tabTrees)
        self.label_10.setGeometry(QtCore.QRect(260, 60, 54, 18))
        self.label_10.setObjectName("label_10")
        self.btnTreeDelete = QtGui.QPushButton(self.tabTrees)
        self.btnTreeDelete.setGeometry(QtCore.QRect(460, 240, 80, 28))
        self.btnTreeDelete.setObjectName("btnTreeDelete")
        self.txtTreeType = QtGui.QLineEdit(self.tabTrees)
        self.txtTreeType.setGeometry(QtCore.QRect(352, 60, 201, 28))
        self.txtTreeType.setObjectName("txtTreeType")
        self.label_19 = QtGui.QLabel(self.tabTrees)
        self.label_19.setGeometry(QtCore.QRect(290, 10, 241, 18))
        self.label_19.setObjectName("label_19")
        self.txtTreeMeasuringUnit = QtGui.QLineEdit(self.tabTrees)
        self.txtTreeMeasuringUnit.setGeometry(QtCore.QRect(350, 110, 201, 28))
        self.txtTreeMeasuringUnit.setObjectName("txtTreeMeasuringUnit")
        self.label_20 = QtGui.QLabel(self.tabTrees)
        self.label_20.setGeometry(QtCore.QRect(0, 10, 221, 18))
        self.label_20.setObjectName("label_20")
        self.label_12 = QtGui.QLabel(self.tabTrees)
        self.label_12.setGeometry(QtCore.QRect(260, 120, 91, 18))
        self.label_12.setObjectName("label_12")
        self.btnTreeSave = QtGui.QPushButton(self.tabTrees)
        self.btnTreeSave.setGeometry(QtCore.QRect(350, 240, 80, 28))
        self.btnTreeSave.setObjectName("btnTreeSave")
        self.treeListView = QtGui.QListView(self.tabTrees)
        self.treeListView.setGeometry(QtCore.QRect(5, 50, 241, 201))
        self.treeListView.setObjectName("treeListView")
        self.tabWidget.addTab(self.tabTrees, "")
        self.tabOtherTradableGoods = QtGui.QWidget()
        self.tabOtherTradableGoods.setObjectName("tabOtherTradableGoods")
        self.label_13 = QtGui.QLabel(self.tabOtherTradableGoods)
        self.label_13.setGeometry(QtCore.QRect(260, 60, 54, 18))
        self.label_13.setObjectName("label_13")
        self.btnTGoodDelete = QtGui.QPushButton(self.tabOtherTradableGoods)
        self.btnTGoodDelete.setGeometry(QtCore.QRect(460, 240, 80, 28))
        self.btnTGoodDelete.setObjectName("btnTGoodDelete")
        self.txtTradableGoodType = QtGui.QLineEdit(self.tabOtherTradableGoods)
        self.txtTradableGoodType.setGeometry(QtCore.QRect(352, 60, 201, 28))
        self.txtTradableGoodType.setObjectName("txtTradableGoodType")
        self.label_21 = QtGui.QLabel(self.tabOtherTradableGoods)
        self.label_21.setGeometry(QtCore.QRect(290, 10, 241, 18))
        self.label_21.setObjectName("label_21")
        self.txtTradableGoodMeasuringUnit = QtGui.QLineEdit(self.tabOtherTradableGoods)
        self.txtTradableGoodMeasuringUnit.setGeometry(QtCore.QRect(350, 110, 201, 28))
        self.txtTradableGoodMeasuringUnit.setObjectName("txtTradableGoodMeasuringUnit")
        self.label_22 = QtGui.QLabel(self.tabOtherTradableGoods)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 221, 18))
        self.label_22.setObjectName("label_22")
        self.label_15 = QtGui.QLabel(self.tabOtherTradableGoods)
        self.label_15.setGeometry(QtCore.QRect(260, 120, 91, 18))
        self.label_15.setObjectName("label_15")
        self.btnTGoodSave = QtGui.QPushButton(self.tabOtherTradableGoods)
        self.btnTGoodSave.setGeometry(QtCore.QRect(350, 240, 80, 28))
        self.btnTGoodSave.setObjectName("btnTGoodSave")
        self.tradableGoodsListView = QtGui.QListView(self.tabOtherTradableGoods)
        self.tradableGoodsListView.setGeometry(QtCore.QRect(0, 50, 251, 192))
        self.tradableGoodsListView.setObjectName("tradableGoodsListView")
        self.tabWidget.addTab(self.tabOtherTradableGoods, "")
        self.tabAssetsGeneral = QtGui.QWidget()
        self.tabAssetsGeneral.setObjectName("tabAssetsGeneral")
        self.txtAssetCategories = QtGui.QLineEdit(self.tabAssetsGeneral)
        self.txtAssetCategories.setGeometry(QtCore.QRect(280, 40, 281, 28))
        self.txtAssetCategories.setObjectName("txtAssetCategories")
        self.btnCatSave = QtGui.QPushButton(self.tabAssetsGeneral)
        self.btnCatSave.setGeometry(QtCore.QRect(280, 120, 80, 28))
        self.btnCatSave.setObjectName("btnCatSave")
        self.btnCatDelete = QtGui.QPushButton(self.tabAssetsGeneral)
        self.btnCatDelete.setGeometry(QtCore.QRect(480, 120, 80, 28))
        self.btnCatDelete.setObjectName("btnCatDelete")
        self.label = QtGui.QLabel(self.tabAssetsGeneral)
        self.label.setGeometry(QtCore.QRect(10, 10, 271, 18))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.tabAssetsGeneral)
        self.label_2.setGeometry(QtCore.QRect(280, 10, 251, 18))
        self.label_2.setObjectName("label_2")
        self.categoriesListView = QtGui.QListView(self.tabAssetsGeneral)
        self.categoriesListView.setGeometry(QtCore.QRect(10, 40, 256, 261))
        self.categoriesListView.setObjectName("categoriesListView")
        self.tabWidget.addTab(self.tabAssetsGeneral, "")
        self.btnAssetsClose = QtGui.QPushButton(ManageAssetDetails)
        self.btnAssetsClose.setGeometry(QtCore.QRect(490, 350, 80, 28))
        self.btnAssetsClose.setObjectName("btnAssetsClose")

        self.retranslateUi(ManageAssetDetails)
        self.tabWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(ManageAssetDetails)

    def retranslateUi(self, ManageAssetDetails):
        ManageAssetDetails.setWindowTitle(QtGui.QApplication.translate("ManageAssetDetails", "Manage Asset Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("ManageAssetDetails", "Cash Saving Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCashDelete.setText(QtGui.QApplication.translate("ManageAssetDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("ManageAssetDetails", "Add/ Edit Cash Saving Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("ManageAssetDetails", "Select Cash Saving Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCashSave.setText(QtGui.QApplication.translate("ManageAssetDetails", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCashSavings), QtGui.QApplication.translate("ManageAssetDetails", "Cash Savings", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFoodStockSave.setText(QtGui.QApplication.translate("ManageAssetDetails", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnFoodStockDelete.setText(QtGui.QApplication.translate("ManageAssetDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ManageAssetDetails", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("ManageAssetDetails", "KCalories", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("ManageAssetDetails", "Select Food Stock Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("ManageAssetDetails", "Add/ Edit Food Stock Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ManageAssetDetails", "Unit of Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFoodStock), QtGui.QApplication.translate("ManageAssetDetails", "Food Stock", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLandSave.setText(QtGui.QApplication.translate("ManageAssetDetails", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("ManageAssetDetails", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("ManageAssetDetails", "Unit of Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("ManageAssetDetails", "Add/ Edit Land Details", None, QtGui.QApplication.UnicodeUTF8))
        self.btnLandDelete.setText(QtGui.QApplication.translate("ManageAssetDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("ManageAssetDetails", "Select Land Type", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLand), QtGui.QApplication.translate("ManageAssetDetails", "Land", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("ManageAssetDetails", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTreeDelete.setText(QtGui.QApplication.translate("ManageAssetDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("ManageAssetDetails", "Add/ Edit Tree Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("ManageAssetDetails", "Select Tree Type", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("ManageAssetDetails", "Unit of Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTreeSave.setText(QtGui.QApplication.translate("ManageAssetDetails", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTrees), QtGui.QApplication.translate("ManageAssetDetails", "Trees", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("ManageAssetDetails", "Type", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTGoodDelete.setText(QtGui.QApplication.translate("ManageAssetDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label_21.setText(QtGui.QApplication.translate("ManageAssetDetails", "Add/ Edit Good Details", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("ManageAssetDetails", "Select Good", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("ManageAssetDetails", "Unit of Measure", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTGoodSave.setText(QtGui.QApplication.translate("ManageAssetDetails", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabOtherTradableGoods), QtGui.QApplication.translate("ManageAssetDetails", "Tradable Goods", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCatSave.setText(QtGui.QApplication.translate("ManageAssetDetails", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCatDelete.setText(QtGui.QApplication.translate("ManageAssetDetails", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ManageAssetDetails", "Existing Asset Categories", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ManageAssetDetails", "Add/Edit Asset Category", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAssetsGeneral), QtGui.QApplication.translate("ManageAssetDetails", "Manage Category Types", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAssetsClose.setText(QtGui.QApplication.translate("ManageAssetDetails", "Close", None, QtGui.QApplication.UnicodeUTF8))

