# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householdsbycharacteristics.ui'
#
# Created: Tue Apr 19 08:13:17 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HouseHoldReport(object):
    def setupUi(self, HouseHoldReport):
        HouseHoldReport.setObjectName(_fromUtf8("HouseHoldReport"))
        HouseHoldReport.resize(596, 399)
        HouseHoldReport.setMinimumSize(QtCore.QSize(596, 399))
        self.cmbHouseholds = QtGui.QComboBox(HouseHoldReport)
        self.cmbHouseholds.setGeometry(QtCore.QRect(186, 50, 171, 22))
        self.cmbHouseholds.setObjectName(_fromUtf8("cmbHouseholds"))
        self.cmbHouseholds.addItem(_fromUtf8(""))
        self.cmbHouseholds.addItem(_fromUtf8(""))
        self.listViewHCharacteristics = QtGui.QListView(HouseHoldReport)
        self.listViewHCharacteristics.setGeometry(QtCore.QRect(6, 110, 171, 281))
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName(_fromUtf8("listViewHCharacteristics"))
        self.cmbOrderCriteria1 = QtGui.QComboBox(HouseHoldReport)
        self.cmbOrderCriteria1.setGeometry(QtCore.QRect(370, 130, 101, 22))
        self.cmbOrderCriteria1.setObjectName(_fromUtf8("cmbOrderCriteria1"))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.cmbOrderCriteria2 = QtGui.QComboBox(HouseHoldReport)
        self.cmbOrderCriteria2.setGeometry(QtCore.QRect(486, 130, 101, 22))
        self.cmbOrderCriteria2.setObjectName(_fromUtf8("cmbOrderCriteria2"))
        self.label = QtGui.QLabel(HouseHoldReport)
        self.label.setGeometry(QtCore.QRect(6, 10, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.cmbProjectNames = QtGui.QComboBox(HouseHoldReport)
        self.cmbProjectNames.setGeometry(QtCore.QRect(186, 10, 361, 22))
        self.cmbProjectNames.setObjectName(_fromUtf8("cmbProjectNames"))
        self.label_2 = QtGui.QLabel(HouseHoldReport)
        self.label_2.setGeometry(QtCore.QRect(6, 50, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(HouseHoldReport)
        self.label_3.setGeometry(QtCore.QRect(6, 90, 161, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(HouseHoldReport)
        self.label_4.setGeometry(QtCore.QRect(370, 110, 111, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(HouseHoldReport)
        self.label_5.setGeometry(QtCore.QRect(486, 110, 161, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cmdGenerateReport = QtGui.QPushButton(HouseHoldReport)
        self.cmdGenerateReport.setGeometry(QtCore.QRect(386, 370, 91, 23))
        self.cmdGenerateReport.setObjectName(_fromUtf8("cmdGenerateReport"))
        self.cmdClose = QtGui.QPushButton(HouseHoldReport)
        self.cmdClose.setGeometry(QtCore.QRect(490, 370, 101, 23))
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.line = QtGui.QFrame(HouseHoldReport)
        self.line.setGeometry(QtCore.QRect(470, 110, 20, 111))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.line_2 = QtGui.QFrame(HouseHoldReport)
        self.line_2.setGeometry(QtCore.QRect(370, 210, 221, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_3 = QtGui.QFrame(HouseHoldReport)
        self.line_3.setGeometry(QtCore.QRect(360, 100, 241, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.frame = QtGui.QFrame(HouseHoldReport)
        self.frame.setGeometry(QtCore.QRect(370, 160, 101, 41))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.opt1Ascending = QtGui.QRadioButton(self.frame)
        self.opt1Ascending.setGeometry(QtCore.QRect(0, 0, 111, 17))
        self.opt1Ascending.setObjectName(_fromUtf8("opt1Ascending"))
        self.opt1Descending = QtGui.QRadioButton(self.frame)
        self.opt1Descending.setGeometry(QtCore.QRect(0, 20, 82, 17))
        self.opt1Descending.setObjectName(_fromUtf8("opt1Descending"))
        self.frame_2 = QtGui.QFrame(HouseHoldReport)
        self.frame_2.setGeometry(QtCore.QRect(490, 160, 101, 41))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.opt2Ascending = QtGui.QRadioButton(self.frame_2)
        self.opt2Ascending.setGeometry(QtCore.QRect(0, 0, 82, 17))
        self.opt2Ascending.setObjectName(_fromUtf8("opt2Ascending"))
        self.opt2Descending = QtGui.QRadioButton(self.frame_2)
        self.opt2Descending.setGeometry(QtCore.QRect(0, 20, 82, 17))
        self.opt2Descending.setObjectName(_fromUtf8("opt2Descending"))
        self.listViewPersonalCharacteristics = QtGui.QListView(HouseHoldReport)
        self.listViewPersonalCharacteristics.setGeometry(QtCore.QRect(190, 110, 171, 281))
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName(_fromUtf8("listViewPersonalCharacteristics"))
        self.label_6 = QtGui.QLabel(HouseHoldReport)
        self.label_6.setGeometry(QtCore.QRect(190, 90, 161, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(HouseHoldReport)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseHoldReport.mdiClose)
        QtCore.QObject.connect(self.cmdGenerateReport, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseHoldReport.getReportData)
        QtCore.QObject.connect(self.cmbProjectNames, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseHoldReport.getHouseholdCharacteristics)
        QtCore.QObject.connect(self.cmbProjectNames, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseHoldReport.getPersonalCharacteristics)
        QtCore.QMetaObject.connectSlotsByName(HouseHoldReport)
        HouseHoldReport.setTabOrder(self.cmbProjectNames, self.cmbHouseholds)
        HouseHoldReport.setTabOrder(self.cmbHouseholds, self.listViewHCharacteristics)
        HouseHoldReport.setTabOrder(self.listViewHCharacteristics, self.listViewPersonalCharacteristics)
        HouseHoldReport.setTabOrder(self.listViewPersonalCharacteristics, self.cmbOrderCriteria1)
        HouseHoldReport.setTabOrder(self.cmbOrderCriteria1, self.cmbOrderCriteria2)
        HouseHoldReport.setTabOrder(self.cmbOrderCriteria2, self.opt1Ascending)
        HouseHoldReport.setTabOrder(self.opt1Ascending, self.opt2Ascending)
        HouseHoldReport.setTabOrder(self.opt2Ascending, self.opt1Descending)
        HouseHoldReport.setTabOrder(self.opt1Descending, self.opt2Descending)
        HouseHoldReport.setTabOrder(self.opt2Descending, self.cmdGenerateReport)
        HouseHoldReport.setTabOrder(self.cmdGenerateReport, self.cmdClose)

    def retranslateUi(self, HouseHoldReport):
        HouseHoldReport.setWindowTitle(QtGui.QApplication.translate("HouseHoldReport", "Report Households by Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbHouseholds.setItemText(0, QtGui.QApplication.translate("HouseHoldReport", "All Households", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbHouseholds.setItemText(1, QtGui.QApplication.translate("HouseHoldReport", "Select by Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(0, QtGui.QApplication.translate("HouseHoldReport", "Household Number", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(1, QtGui.QApplication.translate("HouseHoldReport", "Household Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseHoldReport", "Select Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseHoldReport", "Select Household(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("HouseHoldReport", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HouseHoldReport", "1st Ordering Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("HouseHoldReport", "2nd Ordering Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdGenerateReport.setText(QtGui.QApplication.translate("HouseHoldReport", "Generate Report", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseHoldReport", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Ascending.setText(QtGui.QApplication.translate("HouseHoldReport", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Descending.setText(QtGui.QApplication.translate("HouseHoldReport", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Ascending.setText(QtGui.QApplication.translate("HouseHoldReport", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Descending.setText(QtGui.QApplication.translate("HouseHoldReport", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("HouseHoldReport", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))

