# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householddisposableincome.ui'
#
# Created: Wed Apr 20 16:34:36 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_HouseholdDisposableIncome(object):
    def setupUi(self, HouseholdDisposableIncome):
        HouseholdDisposableIncome.setObjectName("HouseholdDisposableIncome")
        HouseholdDisposableIncome.resize(632, 573)
        HouseholdDisposableIncome.setMinimumSize(QtCore.QSize(632, 573))
        self.cmbProjects = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbProjects.setGeometry(QtCore.QRect(120, 10, 511, 22))
        self.cmbProjects.setObjectName("cmbProjects")
        self.label = QtGui.QLabel(HouseholdDisposableIncome)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label.setObjectName("label")
        self.cmdClose = QtGui.QPushButton(HouseholdDisposableIncome)
        self.cmdClose.setGeometry(QtCore.QRect(510, 530, 101, 31))
        self.cmdClose.setObjectName("cmdClose")
        self.cmdShowReport = QtGui.QPushButton(HouseholdDisposableIncome)
        self.cmdShowReport.setGeometry(QtCore.QRect(380, 530, 111, 31))
        self.cmdShowReport.setObjectName("cmdShowReport")
        self.listViewHCharacteristics = QtGui.QListView(HouseholdDisposableIncome)
        self.listViewHCharacteristics.setGeometry(QtCore.QRect(10, 260, 281, 251))
        self.listViewHCharacteristics.setAlternatingRowColors(True)
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName("listViewHCharacteristics")
        self.listViewPersonalCharacteristics = QtGui.QListView(HouseholdDisposableIncome)
        self.listViewPersonalCharacteristics.setGeometry(QtCore.QRect(310, 260, 311, 251))
        self.listViewPersonalCharacteristics.setAlternatingRowColors(True)
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName("listViewPersonalCharacteristics")
        self.label_4 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 141, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_5.setGeometry(QtCore.QRect(310, 240, 181, 16))
        self.label_5.setObjectName("label_5")
        self.treeViewHouseholds = QtGui.QTreeView(HouseholdDisposableIncome)
        self.treeViewHouseholds.setGeometry(QtCore.QRect(10, 80, 611, 151))
        self.treeViewHouseholds.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeViewHouseholds.setAlternatingRowColors(True)
        self.treeViewHouseholds.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeViewHouseholds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeViewHouseholds.setSortingEnabled(True)
        self.treeViewHouseholds.setObjectName("treeViewHouseholds")
        self.cmdSaveDataTable = QtGui.QPushButton(HouseholdDisposableIncome)
        self.cmdSaveDataTable.setGeometry(QtCore.QRect(280, 530, 91, 31))
        self.cmdSaveDataTable.setObjectName("cmdSaveDataTable")
        self.cmbReportType = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbReportType.setGeometry(QtCore.QRect(120, 40, 281, 22))
        self.cmbReportType.setObjectName("cmbReportType")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.label_2 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(HouseholdDisposableIncome)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL("clicked()"), HouseholdDisposableIncome.mdiClose)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL("currentIndexChanged(int)"), HouseholdDisposableIncome.updateDialogData)
        QtCore.QObject.connect(self.cmdShowReport, QtCore.SIGNAL("clicked()"), HouseholdDisposableIncome.writeTable)
        QtCore.QObject.connect(self.cmdSaveDataTable, QtCore.SIGNAL("clicked()"), HouseholdDisposableIncome.writeTable)
        QtCore.QObject.connect(self.cmbReportType, QtCore.SIGNAL("currentIndexChanged(int)"), HouseholdDisposableIncome.setReportType)
        QtCore.QMetaObject.connectSlotsByName(HouseholdDisposableIncome)
        HouseholdDisposableIncome.setTabOrder(self.cmbProjects, self.cmbReportType)
        HouseholdDisposableIncome.setTabOrder(self.cmbReportType, self.treeViewHouseholds)
        HouseholdDisposableIncome.setTabOrder(self.treeViewHouseholds, self.listViewHCharacteristics)
        HouseholdDisposableIncome.setTabOrder(self.listViewHCharacteristics, self.listViewPersonalCharacteristics)
        HouseholdDisposableIncome.setTabOrder(self.listViewPersonalCharacteristics, self.cmdSaveDataTable)
        HouseholdDisposableIncome.setTabOrder(self.cmdSaveDataTable, self.cmdShowReport)
        HouseholdDisposableIncome.setTabOrder(self.cmdShowReport, self.cmdClose)

    def retranslateUi(self, HouseholdDisposableIncome):
        HouseholdDisposableIncome.setWindowTitle(QtGui.QApplication.translate("HouseholdDisposableIncome", "Report: Households by Income Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdShowReport.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Show Report", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveDataTable.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Save Data Table", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(0, QtGui.QApplication.translate("HouseholdDisposableIncome", "Disposable Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(1, QtGui.QApplication.translate("HouseholdDisposableIncome", "Disposable Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(2, QtGui.QApplication.translate("HouseholdDisposableIncome", "Living Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Report Type", None, QtGui.QApplication.UnicodeUTF8))

