# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householdincome.ui'
#
# Created: Thu Apr 21 20:06:25 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HouseholdIncomeReport(object):
    def setupUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setObjectName(_fromUtf8("HouseholdIncomeReport"))
        HouseholdIncomeReport.resize(713, 580)
        HouseholdIncomeReport.setMinimumSize(QtCore.QSize(632, 580))
        self.formLayout = QtGui.QFormLayout(HouseholdIncomeReport)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(HouseholdIncomeReport)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cmbProjects = QtGui.QComboBox(HouseholdIncomeReport)
        self.cmbProjects.setObjectName(_fromUtf8("cmbProjects"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbProjects)
        self.label_2 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cmbReportType = QtGui.QComboBox(HouseholdIncomeReport)
        self.cmbReportType.setObjectName(_fromUtf8("cmbReportType"))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbReportType)
        self.treeViewHouseholds = QtGui.QTreeView(HouseholdIncomeReport)
        self.treeViewHouseholds.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeViewHouseholds.setAlternatingRowColors(True)
        self.treeViewHouseholds.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeViewHouseholds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeViewHouseholds.setSortingEnabled(True)
        self.treeViewHouseholds.setObjectName(_fromUtf8("treeViewHouseholds"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.treeViewHouseholds)
        self.groupBox_4 = QtGui.QGroupBox(HouseholdIncomeReport)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.treeView = QtGui.QTreeView(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeView.setSortingEnabled(False)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.verticalLayout_3.addWidget(self.treeView)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.listViewHCharacteristics = QtGui.QListView(self.groupBox_2)
        self.listViewHCharacteristics.setAlternatingRowColors(True)
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName(_fromUtf8("listViewHCharacteristics"))
        self.verticalLayout.addWidget(self.listViewHCharacteristics)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.listViewPersonalCharacteristics = QtGui.QListView(self.groupBox_3)
        self.listViewPersonalCharacteristics.setAlternatingRowColors(True)
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName(_fromUtf8("listViewPersonalCharacteristics"))
        self.verticalLayout_2.addWidget(self.listViewPersonalCharacteristics)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(HouseholdIncomeReport)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdSaveDataTable = QtGui.QPushButton(self.groupBox)
        self.cmdSaveDataTable.setObjectName(_fromUtf8("cmdSaveDataTable"))
        self.horizontalLayout.addWidget(self.cmdSaveDataTable)
        self.cmdShowReport = QtGui.QPushButton(self.groupBox)
        self.cmdShowReport.setObjectName(_fromUtf8("cmdShowReport"))
        self.horizontalLayout.addWidget(self.cmdShowReport)
        self.cmdClose = QtGui.QPushButton(self.groupBox)
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.horizontalLayout.addWidget(self.cmdClose)
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.groupBox)

        self.retranslateUi(HouseholdIncomeReport)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL(_fromUtf8("activated(QString)")), HouseholdIncomeReport.updateDialogData)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseholdIncomeReport.putMainIncomeCategories)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdIncomeReport.mdiClose)
        QtCore.QObject.connect(self.cmdShowReport, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdIncomeReport.getReportTable)
        QtCore.QObject.connect(self.cmdSaveDataTable, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdIncomeReport.writeTable)
        QtCore.QMetaObject.connectSlotsByName(HouseholdIncomeReport)
        HouseholdIncomeReport.setTabOrder(self.cmbProjects, self.cmbReportType)
        HouseholdIncomeReport.setTabOrder(self.cmbReportType, self.treeViewHouseholds)

    def retranslateUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setWindowTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Report: Households by Income Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Report Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(0, QtGui.QApplication.translate("HouseholdIncomeReport", "Cash Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(1, QtGui.QApplication.translate("HouseholdIncomeReport", "Cash Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(2, QtGui.QApplication.translate("HouseholdIncomeReport", "Food Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(3, QtGui.QApplication.translate("HouseholdIncomeReport", "Food Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveDataTable.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Save Data Table", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdShowReport.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Show Report", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Close", None, QtGui.QApplication.UnicodeUTF8))

