# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householdincome.ui'
#
# Created: Fri Jul 29 20:32:02 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_HouseholdIncomeReport(object):
    def setupUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setObjectName("HouseholdIncomeReport")
        HouseholdIncomeReport.resize(713, 606)
        HouseholdIncomeReport.setMinimumSize(QtCore.QSize(632, 580))
        self.verticalLayout_4 = QtGui.QVBoxLayout(HouseholdIncomeReport)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtGui.QFrame(HouseholdIncomeReport)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtGui.QFormLayout(self.frame_2)
        self.formLayout.setObjectName("formLayout")
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cmbProjects = QtGui.QComboBox(self.frame_2)
        self.cmbProjects.setObjectName("cmbProjects")
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbProjects)
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cmbReportType = QtGui.QComboBox(self.frame_2)
        self.cmbReportType.setObjectName("cmbReportType")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbReportType)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(HouseholdIncomeReport)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.treeViewHouseholds = QtGui.QTreeView(self.frame)
        self.treeViewHouseholds.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeViewHouseholds.setAlternatingRowColors(True)
        self.treeViewHouseholds.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeViewHouseholds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeViewHouseholds.setSortingEnabled(True)
        self.treeViewHouseholds.setObjectName("treeViewHouseholds")
        self.gridLayout_2.addWidget(self.treeViewHouseholds, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.frame)
        self.groupBox_4 = QtGui.QGroupBox(HouseholdIncomeReport)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.groupBox_5 = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setObjectName("groupBox_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.treeView = QtGui.QTreeView(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.treeView.sizePolicy().hasHeightForWidth())
        self.treeView.setSizePolicy(sizePolicy)
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeView.setSortingEnabled(False)
        self.treeView.setObjectName("treeView")
        self.verticalLayout_3.addWidget(self.treeView)
        self.horizontalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listViewHCharacteristics = QtGui.QListView(self.groupBox_2)
        self.listViewHCharacteristics.setAlternatingRowColors(True)
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName("listViewHCharacteristics")
        self.verticalLayout.addWidget(self.listViewHCharacteristics)
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listViewPersonalCharacteristics = QtGui.QListView(self.groupBox_3)
        self.listViewPersonalCharacteristics.setAlternatingRowColors(True)
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName("listViewPersonalCharacteristics")
        self.verticalLayout_2.addWidget(self.listViewPersonalCharacteristics)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.verticalLayout_4.addWidget(self.groupBox_4)
        self.groupBox = QtGui.QGroupBox(HouseholdIncomeReport)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.cmdSaveDataTable = QtGui.QPushButton(self.groupBox)
        self.cmdSaveDataTable.setObjectName("cmdSaveDataTable")
        self.gridLayout.addWidget(self.cmdSaveDataTable, 0, 0, 1, 1)
        self.cmdShowReport = QtGui.QPushButton(self.groupBox)
        self.cmdShowReport.setObjectName("cmdShowReport")
        self.gridLayout.addWidget(self.cmdShowReport, 0, 1, 1, 1)
        self.cmdClose = QtGui.QPushButton(self.groupBox)
        self.cmdClose.setObjectName("cmdClose")
        self.gridLayout.addWidget(self.cmdClose, 0, 2, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.label.setBuddy(self.cmbProjects)
        self.label_2.setBuddy(self.cmbReportType)

        self.retranslateUi(HouseholdIncomeReport)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL("activated(QString)"), HouseholdIncomeReport.updateDialogData)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL("currentIndexChanged(int)"), HouseholdIncomeReport.putMainIncomeCategories)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL("clicked()"), HouseholdIncomeReport.mdiClose)
        QtCore.QObject.connect(self.cmdShowReport, QtCore.SIGNAL("clicked()"), HouseholdIncomeReport.writeTable)
        QtCore.QObject.connect(self.cmdSaveDataTable, QtCore.SIGNAL("clicked()"), HouseholdIncomeReport.writeTable)
        QtCore.QMetaObject.connectSlotsByName(HouseholdIncomeReport)
        HouseholdIncomeReport.setTabOrder(self.cmbProjects, self.cmbReportType)
        HouseholdIncomeReport.setTabOrder(self.cmbReportType, self.treeViewHouseholds)
        HouseholdIncomeReport.setTabOrder(self.treeViewHouseholds, self.treeView)
        HouseholdIncomeReport.setTabOrder(self.treeView, self.listViewHCharacteristics)
        HouseholdIncomeReport.setTabOrder(self.listViewHCharacteristics, self.listViewPersonalCharacteristics)
        HouseholdIncomeReport.setTabOrder(self.listViewPersonalCharacteristics, self.cmdSaveDataTable)
        HouseholdIncomeReport.setTabOrder(self.cmdSaveDataTable, self.cmdShowReport)
        HouseholdIncomeReport.setTabOrder(self.cmdShowReport, self.cmdClose)

    def retranslateUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setWindowTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Report: Households by Income Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Report Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(0, QtGui.QApplication.translate("HouseholdIncomeReport", "Cash Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(1, QtGui.QApplication.translate("HouseholdIncomeReport", "Cash Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(2, QtGui.QApplication.translate("HouseholdIncomeReport", "Food Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(3, QtGui.QApplication.translate("HouseholdIncomeReport", "Food Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveDataTable.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Save Data Table", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdShowReport.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Show Report", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Close", None, QtGui.QApplication.UnicodeUTF8))

