# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householddisposableincome.ui'
#
# Created: Fri Apr 22 15:47:24 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HouseholdDisposableIncome(object):
    def setupUi(self, HouseholdDisposableIncome):
        HouseholdDisposableIncome.setObjectName(_fromUtf8("HouseholdDisposableIncome"))
        HouseholdDisposableIncome.resize(669, 574)
        HouseholdDisposableIncome.setMinimumSize(QtCore.QSize(580, 550))
        self.formLayout = QtGui.QFormLayout(HouseholdDisposableIncome)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(HouseholdDisposableIncome)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.cmbProjects = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbProjects.setObjectName(_fromUtf8("cmbProjects"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbProjects)
        self.label_2 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.cmbReportType = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbReportType.setObjectName(_fromUtf8("cmbReportType"))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.cmbReportType)
        self.treeViewHouseholds = QtGui.QTreeView(HouseholdDisposableIncome)
        self.treeViewHouseholds.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeViewHouseholds.setAlternatingRowColors(True)
        self.treeViewHouseholds.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeViewHouseholds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeViewHouseholds.setSortingEnabled(True)
        self.treeViewHouseholds.setObjectName(_fromUtf8("treeViewHouseholds"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.treeViewHouseholds)
        self.frame = QtGui.QFrame(HouseholdDisposableIncome)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 220))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.listViewHCharacteristics = QtGui.QListView(self.groupBox)
        self.listViewHCharacteristics.setGeometry(QtCore.QRect(0, 20, 256, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewHCharacteristics.sizePolicy().hasHeightForWidth())
        self.listViewHCharacteristics.setSizePolicy(sizePolicy)
        self.listViewHCharacteristics.setAlternatingRowColors(True)
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName(_fromUtf8("listViewHCharacteristics"))
        self.horizontalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.frame)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.listViewPersonalCharacteristics = QtGui.QListView(self.groupBox_2)
        self.listViewPersonalCharacteristics.setGeometry(QtCore.QRect(0, 20, 256, 192))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewPersonalCharacteristics.sizePolicy().hasHeightForWidth())
        self.listViewPersonalCharacteristics.setSizePolicy(sizePolicy)
        self.listViewPersonalCharacteristics.setAlternatingRowColors(True)
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName(_fromUtf8("listViewPersonalCharacteristics"))
        self.horizontalLayout_2.addWidget(self.groupBox_2)
        self.formLayout.setWidget(3, QtGui.QFormLayout.SpanningRole, self.frame)
        self.groupBox_3 = QtGui.QGroupBox(HouseholdDisposableIncome)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cmdSaveDataTable = QtGui.QPushButton(self.groupBox_3)
        self.cmdSaveDataTable.setObjectName(_fromUtf8("cmdSaveDataTable"))
        self.horizontalLayout.addWidget(self.cmdSaveDataTable)
        self.cmdShowReport = QtGui.QPushButton(self.groupBox_3)
        self.cmdShowReport.setObjectName(_fromUtf8("cmdShowReport"))
        self.horizontalLayout.addWidget(self.cmdShowReport)
        self.cmdClose = QtGui.QPushButton(self.groupBox_3)
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.horizontalLayout.addWidget(self.cmdClose)
        self.formLayout.setWidget(4, QtGui.QFormLayout.SpanningRole, self.groupBox_3)

        self.retranslateUi(HouseholdDisposableIncome)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdDisposableIncome.mdiClose)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseholdDisposableIncome.updateDialogData)
        QtCore.QObject.connect(self.cmdShowReport, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdDisposableIncome.writeTable)
        QtCore.QObject.connect(self.cmdSaveDataTable, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdDisposableIncome.writeTable)
        QtCore.QObject.connect(self.cmbReportType, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseholdDisposableIncome.setReportType)
        QtCore.QMetaObject.connectSlotsByName(HouseholdDisposableIncome)
        HouseholdDisposableIncome.setTabOrder(self.cmbProjects, self.cmbReportType)
        HouseholdDisposableIncome.setTabOrder(self.cmbReportType, self.treeViewHouseholds)
        HouseholdDisposableIncome.setTabOrder(self.treeViewHouseholds, self.cmdSaveDataTable)
        HouseholdDisposableIncome.setTabOrder(self.cmdSaveDataTable, self.cmdClose)

    def retranslateUi(self, HouseholdDisposableIncome):
        HouseholdDisposableIncome.setWindowTitle(QtGui.QApplication.translate("HouseholdDisposableIncome", "Report: Households by Income Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Report Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(0, QtGui.QApplication.translate("HouseholdDisposableIncome", "Disposable Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(1, QtGui.QApplication.translate("HouseholdDisposableIncome", "Disposable Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(2, QtGui.QApplication.translate("HouseholdDisposableIncome", "Living Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("HouseholdDisposableIncome", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("HouseholdDisposableIncome", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveDataTable.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Save Data Table", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdShowReport.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Show Report", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Close", None, QtGui.QApplication.UnicodeUTF8))

