# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householdincome.ui'
#
# Created: Wed Apr 20 16:35:49 2011
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_HouseholdIncomeReport(object):
    def setupUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setObjectName("HouseholdIncomeReport")
        HouseholdIncomeReport.resize(632, 580)
        HouseholdIncomeReport.setMinimumSize(QtCore.QSize(632, 580))
        self.cmbProjects = QtGui.QComboBox(HouseholdIncomeReport)
        self.cmbProjects.setGeometry(QtCore.QRect(120, 10, 511, 22))
        self.cmbProjects.setObjectName("cmbProjects")
        self.label = QtGui.QLabel(HouseholdIncomeReport)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label.setObjectName("label")
        self.cmdClose = QtGui.QPushButton(HouseholdIncomeReport)
        self.cmdClose.setGeometry(QtCore.QRect(520, 540, 101, 31))
        self.cmdClose.setObjectName("cmdClose")
        self.cmdShowReport = QtGui.QPushButton(HouseholdIncomeReport)
        self.cmdShowReport.setGeometry(QtCore.QRect(410, 540, 91, 31))
        self.cmdShowReport.setObjectName("cmdShowReport")
        self.treeView = QtGui.QTreeView(HouseholdIncomeReport)
        self.treeView.setGeometry(QtCore.QRect(10, 260, 201, 271))
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeView.setSortingEnabled(False)
        self.treeView.setObjectName("treeView")
        self.listViewHCharacteristics = QtGui.QListView(HouseholdIncomeReport)
        self.listViewHCharacteristics.setGeometry(QtCore.QRect(220, 260, 201, 271))
        self.listViewHCharacteristics.setAlternatingRowColors(True)
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName("listViewHCharacteristics")
        self.listViewPersonalCharacteristics = QtGui.QListView(HouseholdIncomeReport)
        self.listViewPersonalCharacteristics.setGeometry(QtCore.QRect(430, 260, 191, 271))
        self.listViewPersonalCharacteristics.setAlternatingRowColors(True)
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName("listViewPersonalCharacteristics")
        self.label_4 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_4.setGeometry(QtCore.QRect(225, 240, 141, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_5.setGeometry(QtCore.QRect(430, 240, 181, 16))
        self.label_5.setObjectName("label_5")
        self.treeViewHouseholds = QtGui.QTreeView(HouseholdIncomeReport)
        self.treeViewHouseholds.setGeometry(QtCore.QRect(10, 80, 611, 151))
        self.treeViewHouseholds.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeViewHouseholds.setAlternatingRowColors(True)
        self.treeViewHouseholds.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeViewHouseholds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeViewHouseholds.setSortingEnabled(True)
        self.treeViewHouseholds.setObjectName("treeViewHouseholds")
        self.cmdSaveDataTable = QtGui.QPushButton(HouseholdIncomeReport)
        self.cmdSaveDataTable.setGeometry(QtCore.QRect(300, 540, 91, 31))
        self.cmdSaveDataTable.setObjectName("cmdSaveDataTable")
        self.cmbReportType = QtGui.QComboBox(HouseholdIncomeReport)
        self.cmbReportType.setGeometry(QtCore.QRect(120, 40, 281, 22))
        self.cmbReportType.setObjectName("cmbReportType")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.cmbReportType.addItem("")
        self.label_2 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(HouseholdIncomeReport)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL("clicked()"), HouseholdIncomeReport.mdiClose)
        QtCore.QObject.connect(self.cmdSaveDataTable, QtCore.SIGNAL("clicked()"), HouseholdIncomeReport.writeTable)
        QtCore.QObject.connect(self.cmdShowReport, QtCore.SIGNAL("clicked()"), HouseholdIncomeReport.getReportTable)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL("activated(QString)"), HouseholdIncomeReport.updateDialogData)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL("currentIndexChanged(int)"), HouseholdIncomeReport.putMainIncomeCategories)
        QtCore.QMetaObject.connectSlotsByName(HouseholdIncomeReport)
        HouseholdIncomeReport.setTabOrder(self.cmbProjects, self.cmbReportType)
        HouseholdIncomeReport.setTabOrder(self.cmbReportType, self.treeViewHouseholds)
        HouseholdIncomeReport.setTabOrder(self.treeViewHouseholds, self.treeView)
        HouseholdIncomeReport.setTabOrder(self.treeView, self.listViewHCharacteristics)
        HouseholdIncomeReport.setTabOrder(self.listViewHCharacteristics, self.listViewPersonalCharacteristics)
        HouseholdIncomeReport.setTabOrder(self.listViewPersonalCharacteristics, self.cmdSaveDataTable)
        HouseholdIncomeReport.setTabOrder(self.cmdSaveDataTable, self.cmdShowReport)
        HouseholdIncomeReport.setTabOrder(self.cmdShowReport, self.cmdClose)

    def retranslateUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setWindowTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Report: Households by Income Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdShowReport.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Show Report", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveDataTable.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Save Data Table", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(0, QtGui.QApplication.translate("HouseholdIncomeReport", "Cash Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(1, QtGui.QApplication.translate("HouseholdIncomeReport", "Cash Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(2, QtGui.QApplication.translate("HouseholdIncomeReport", "Food Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(3, QtGui.QApplication.translate("HouseholdIncomeReport", "Food Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Report Type", None, QtGui.QApplication.UnicodeUTF8))

