# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householdincome_byname.ui'
#
# Created: Tue Apr 19 10:36:39 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HouseholdIncomeReport(object):
    def setupUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setObjectName(_fromUtf8("HouseholdIncomeReport"))
        HouseholdIncomeReport.resize(632, 628)
        HouseholdIncomeReport.setMinimumSize(QtCore.QSize(632, 628))
        self.cmbProjects = QtGui.QComboBox(HouseholdIncomeReport)
        self.cmbProjects.setGeometry(QtCore.QRect(80, 10, 551, 22))
        self.cmbProjects.setObjectName(_fromUtf8("cmbProjects"))
        self.label = QtGui.QLabel(HouseholdIncomeReport)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_3.setGeometry(QtCore.QRect(10, 200, 191, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.cmdClose = QtGui.QPushButton(HouseholdIncomeReport)
        self.cmdClose.setGeometry(QtCore.QRect(530, 600, 101, 23))
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.cmdShowReport = QtGui.QPushButton(HouseholdIncomeReport)
        self.cmdShowReport.setGeometry(QtCore.QRect(410, 600, 111, 23))
        self.cmdShowReport.setObjectName(_fromUtf8("cmdShowReport"))
        self.treeView = QtGui.QTreeView(HouseholdIncomeReport)
        self.treeView.setGeometry(QtCore.QRect(10, 220, 201, 291))
        self.treeView.setAlternatingRowColors(True)
        self.treeView.setSortingEnabled(True)
        self.treeView.setObjectName(_fromUtf8("treeView"))
        self.listViewHCharacteristics = QtGui.QListView(HouseholdIncomeReport)
        self.listViewHCharacteristics.setGeometry(QtCore.QRect(220, 220, 201, 291))
        self.listViewHCharacteristics.setAlternatingRowColors(True)
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName(_fromUtf8("listViewHCharacteristics"))
        self.listViewPersonalCharacteristics = QtGui.QListView(HouseholdIncomeReport)
        self.listViewPersonalCharacteristics.setGeometry(QtCore.QRect(430, 220, 191, 291))
        self.listViewPersonalCharacteristics.setAlternatingRowColors(True)
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName(_fromUtf8("listViewPersonalCharacteristics"))
        self.label_4 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_4.setGeometry(QtCore.QRect(225, 200, 141, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_5.setGeometry(QtCore.QRect(430, 200, 181, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_5 = QtGui.QFrame(HouseholdIncomeReport)
        self.line_5.setGeometry(QtCore.QRect(0, 510, 631, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.listView = QtGui.QListView(HouseholdIncomeReport)
        self.listView.setGeometry(QtCore.QRect(70, 50, 551, 141))
        self.listView.setMinimumSize(QtCore.QSize(0, 0))
        self.listView.setAlternatingRowColors(True)
        self.listView.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.label_8 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_8.setGeometry(QtCore.QRect(10, 520, 241, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.frame_2 = QtGui.QFrame(HouseholdIncomeReport)
        self.frame_2.setGeometry(QtCore.QRect(430, 560, 181, 21))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.opt2Ascending = QtGui.QRadioButton(self.frame_2)
        self.opt2Ascending.setGeometry(QtCore.QRect(10, 0, 82, 17))
        self.opt2Ascending.setObjectName(_fromUtf8("opt2Ascending"))
        self.opt2Descending = QtGui.QRadioButton(self.frame_2)
        self.opt2Descending.setGeometry(QtCore.QRect(100, 0, 82, 17))
        self.opt2Descending.setObjectName(_fromUtf8("opt2Descending"))
        self.cmbOrderCriteria2 = QtGui.QComboBox(HouseholdIncomeReport)
        self.cmbOrderCriteria2.setGeometry(QtCore.QRect(320, 560, 101, 22))
        self.cmbOrderCriteria2.setObjectName(_fromUtf8("cmbOrderCriteria2"))
        self.line_3 = QtGui.QFrame(HouseholdIncomeReport)
        self.line_3.setGeometry(QtCore.QRect(0, 530, 631, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.cmbOrderCriteria1 = QtGui.QComboBox(HouseholdIncomeReport)
        self.cmbOrderCriteria1.setGeometry(QtCore.QRect(10, 560, 101, 22))
        self.cmbOrderCriteria1.setObjectName(_fromUtf8("cmbOrderCriteria1"))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.frame = QtGui.QFrame(HouseholdIncomeReport)
        self.frame.setGeometry(QtCore.QRect(130, 560, 171, 21))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.opt1Ascending = QtGui.QRadioButton(self.frame)
        self.opt1Ascending.setGeometry(QtCore.QRect(10, 0, 111, 17))
        self.opt1Ascending.setObjectName(_fromUtf8("opt1Ascending"))
        self.opt1Descending = QtGui.QRadioButton(self.frame)
        self.opt1Descending.setGeometry(QtCore.QRect(90, 0, 82, 17))
        self.opt1Descending.setObjectName(_fromUtf8("opt1Descending"))
        self.line_2 = QtGui.QFrame(HouseholdIncomeReport)
        self.line_2.setGeometry(QtCore.QRect(0, 580, 631, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.label_7 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_7.setGeometry(QtCore.QRect(320, 540, 111, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_6 = QtGui.QLabel(HouseholdIncomeReport)
        self.label_6.setGeometry(QtCore.QRect(10, 540, 111, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line = QtGui.QFrame(HouseholdIncomeReport)
        self.line.setGeometry(QtCore.QRect(300, 540, 20, 51))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))

        self.retranslateUi(HouseholdIncomeReport)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdIncomeReport.mdiClose)
        QtCore.QObject.connect(self.cmdShowReport, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseholdIncomeReport.writeTable)
        QtCore.QObject.connect(self.cmbProjects, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseholdIncomeReport.updateDialogData)
        QtCore.QMetaObject.connectSlotsByName(HouseholdIncomeReport)
        HouseholdIncomeReport.setTabOrder(self.cmbProjects, self.listView)
        HouseholdIncomeReport.setTabOrder(self.listView, self.treeView)
        HouseholdIncomeReport.setTabOrder(self.treeView, self.listViewHCharacteristics)
        HouseholdIncomeReport.setTabOrder(self.listViewHCharacteristics, self.listViewPersonalCharacteristics)
        HouseholdIncomeReport.setTabOrder(self.listViewPersonalCharacteristics, self.cmbOrderCriteria1)
        HouseholdIncomeReport.setTabOrder(self.cmbOrderCriteria1, self.opt1Ascending)
        HouseholdIncomeReport.setTabOrder(self.opt1Ascending, self.opt1Descending)
        HouseholdIncomeReport.setTabOrder(self.opt1Descending, self.cmbOrderCriteria2)
        HouseholdIncomeReport.setTabOrder(self.cmbOrderCriteria2, self.opt2Ascending)
        HouseholdIncomeReport.setTabOrder(self.opt2Ascending, self.opt2Descending)
        HouseholdIncomeReport.setTabOrder(self.opt2Descending, self.cmdShowReport)
        HouseholdIncomeReport.setTabOrder(self.cmdShowReport, self.cmdClose)

    def retranslateUi(self, HouseholdIncomeReport):
        HouseholdIncomeReport.setWindowTitle(QtGui.QApplication.translate("HouseholdIncomeReport", "Report: Households by Income Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Households", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Income Sources", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdShowReport.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Show Report", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Report Data Sort Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Ascending.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Descending.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(0, QtGui.QApplication.translate("HouseholdIncomeReport", "Household Number", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(1, QtGui.QApplication.translate("HouseholdIncomeReport", "Household Name", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Ascending.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Descending.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "2nd Ordering Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("HouseholdIncomeReport", "1st Ordering Criteria", None, QtGui.QApplication.UnicodeUTF8))

