# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householdsbycharacteristics.ui'
#
# Created: Fri Apr 22 21:39:25 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HouseHoldReport(object):
    def setupUi(self, HouseHoldReport):
        HouseHoldReport.setObjectName(_fromUtf8("HouseHoldReport"))
        HouseHoldReport.resize(760, 452)
        HouseHoldReport.setMinimumSize(QtCore.QSize(596, 399))
        self.gridLayout = QtGui.QGridLayout(HouseHoldReport)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(HouseHoldReport)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.cmbProjectNames = QtGui.QComboBox(HouseHoldReport)
        self.cmbProjectNames.setObjectName(_fromUtf8("cmbProjectNames"))
        self.gridLayout.addWidget(self.cmbProjectNames, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(HouseHoldReport)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.cmbHouseholds = QtGui.QComboBox(HouseHoldReport)
        self.cmbHouseholds.setObjectName(_fromUtf8("cmbHouseholds"))
        self.cmbHouseholds.addItem(_fromUtf8(""))
        self.cmbHouseholds.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.cmbHouseholds, 1, 1, 1, 2)
        self.groupBox = QtGui.QGroupBox(HouseHoldReport)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.listViewHCharacteristics = QtGui.QListView(self.groupBox)
        self.listViewHCharacteristics.setAlternatingRowColors(True)
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName(_fromUtf8("listViewHCharacteristics"))
        self.verticalLayout_6.addWidget(self.listViewHCharacteristics)
        self.gridLayout.addWidget(self.groupBox, 2, 0, 2, 2)
        self.groupBox_2 = QtGui.QGroupBox(HouseHoldReport)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.listViewPersonalCharacteristics = QtGui.QListView(self.groupBox_2)
        self.listViewPersonalCharacteristics.setAlternatingRowColors(True)
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName(_fromUtf8("listViewPersonalCharacteristics"))
        self.verticalLayout_5.addWidget(self.listViewPersonalCharacteristics)
        self.gridLayout.addWidget(self.groupBox_2, 2, 2, 2, 2)
        self.groupBox_3 = QtGui.QGroupBox(HouseHoldReport)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.cmbOrderCriteria1 = QtGui.QComboBox(self.groupBox_3)
        self.cmbOrderCriteria1.setObjectName(_fromUtf8("cmbOrderCriteria1"))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.verticalLayout_3.addWidget(self.cmbOrderCriteria1)
        self.frame = QtGui.QFrame(self.groupBox_3)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.opt1Ascending = QtGui.QRadioButton(self.frame)
        self.opt1Ascending.setObjectName(_fromUtf8("opt1Ascending"))
        self.verticalLayout.addWidget(self.opt1Ascending)
        self.opt1Descending = QtGui.QRadioButton(self.frame)
        self.opt1Descending.setObjectName(_fromUtf8("opt1Descending"))
        self.verticalLayout.addWidget(self.opt1Descending)
        self.verticalLayout_3.addWidget(self.frame)
        self.gridLayout.addWidget(self.groupBox_3, 2, 4, 1, 2)
        self.groupBox_4 = QtGui.QGroupBox(HouseHoldReport)
        self.groupBox_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.cmbOrderCriteria2 = QtGui.QComboBox(self.groupBox_4)
        self.cmbOrderCriteria2.setObjectName(_fromUtf8("cmbOrderCriteria2"))
        self.verticalLayout_4.addWidget(self.cmbOrderCriteria2)
        self.frame_2 = QtGui.QFrame(self.groupBox_4)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.opt2Ascending = QtGui.QRadioButton(self.frame_2)
        self.opt2Ascending.setObjectName(_fromUtf8("opt2Ascending"))
        self.verticalLayout_2.addWidget(self.opt2Ascending)
        self.opt2Descending = QtGui.QRadioButton(self.frame_2)
        self.opt2Descending.setObjectName(_fromUtf8("opt2Descending"))
        self.verticalLayout_2.addWidget(self.opt2Descending)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.gridLayout.addWidget(self.groupBox_4, 3, 4, 1, 2)
        self.cmdGenerateReport = QtGui.QPushButton(HouseHoldReport)
        self.cmdGenerateReport.setObjectName(_fromUtf8("cmdGenerateReport"))
        self.gridLayout.addWidget(self.cmdGenerateReport, 4, 3, 1, 2)
        self.cmdClose = QtGui.QPushButton(HouseHoldReport)
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.gridLayout.addWidget(self.cmdClose, 4, 5, 1, 1)

        self.retranslateUi(HouseHoldReport)
        QtCore.QObject.connect(self.cmdClose, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseHoldReport.mdiClose)
        QtCore.QObject.connect(self.cmdGenerateReport, QtCore.SIGNAL(_fromUtf8("clicked()")), HouseHoldReport.writeSpreadsheet)
        QtCore.QObject.connect(self.cmbProjectNames, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseHoldReport.getHouseholdCharacteristics)
        QtCore.QObject.connect(self.cmbProjectNames, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), HouseHoldReport.getPersonalCharacteristics)
        QtCore.QMetaObject.connectSlotsByName(HouseHoldReport)
        HouseHoldReport.setTabOrder(self.cmbProjectNames, self.cmbHouseholds)
        HouseHoldReport.setTabOrder(self.cmbHouseholds, self.listViewHCharacteristics)
        HouseHoldReport.setTabOrder(self.listViewHCharacteristics, self.listViewPersonalCharacteristics)
        HouseHoldReport.setTabOrder(self.listViewPersonalCharacteristics, self.cmbOrderCriteria1)
        HouseHoldReport.setTabOrder(self.cmbOrderCriteria1, self.opt1Ascending)
        HouseHoldReport.setTabOrder(self.opt1Ascending, self.opt1Descending)
        HouseHoldReport.setTabOrder(self.opt1Descending, self.cmbOrderCriteria2)
        HouseHoldReport.setTabOrder(self.cmbOrderCriteria2, self.opt2Ascending)
        HouseHoldReport.setTabOrder(self.opt2Ascending, self.opt2Descending)
        HouseHoldReport.setTabOrder(self.opt2Descending, self.cmdGenerateReport)
        HouseHoldReport.setTabOrder(self.cmdGenerateReport, self.cmdClose)

    def retranslateUi(self, HouseHoldReport):
        HouseHoldReport.setWindowTitle(QtGui.QApplication.translate("HouseHoldReport", "Report Households by Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseHoldReport", "Select Project Name", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseHoldReport", "Select Household(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbHouseholds.setItemText(0, QtGui.QApplication.translate("HouseHoldReport", "All Households", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbHouseholds.setItemText(1, QtGui.QApplication.translate("HouseHoldReport", "Select by Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("HouseHoldReport", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("HouseHoldReport", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("HouseHoldReport", "1st Ordering Criterion", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(0, QtGui.QApplication.translate("HouseHoldReport", "Household Number", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(1, QtGui.QApplication.translate("HouseHoldReport", "Household Name", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Ascending.setText(QtGui.QApplication.translate("HouseHoldReport", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Descending.setText(QtGui.QApplication.translate("HouseHoldReport", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("HouseHoldReport", "2nd Ordering Criterion", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Ascending.setText(QtGui.QApplication.translate("HouseHoldReport", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Descending.setText(QtGui.QApplication.translate("HouseHoldReport", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdGenerateReport.setText(QtGui.QApplication.translate("HouseHoldReport", "Generate Report", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseHoldReport", "Close", None, QtGui.QApplication.UnicodeUTF8))

