# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_report_householddisposableincome.ui'
#
# Created: Thu Feb 17 14:28:09 2011
#      by: PyQt4 UI code generator 4.7.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_HouseholdDisposableIncome(object):
    def setupUi(self, HouseholdDisposableIncome):
        HouseholdDisposableIncome.setObjectName(_fromUtf8("HouseholdDisposableIncome"))
        HouseholdDisposableIncome.resize(632, 654)
        HouseholdDisposableIncome.setMinimumSize(QtCore.QSize(632, 654))
        self.cmbProjects = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbProjects.setGeometry(QtCore.QRect(120, 10, 511, 22))
        self.cmbProjects.setObjectName(_fromUtf8("cmbProjects"))
        self.label = QtGui.QLabel(HouseholdDisposableIncome)
        self.label.setGeometry(QtCore.QRect(10, 20, 46, 13))
        self.label.setObjectName(_fromUtf8("label"))
        self.cmdClose = QtGui.QPushButton(HouseholdDisposableIncome)
        self.cmdClose.setGeometry(QtCore.QRect(530, 630, 101, 23))
        self.cmdClose.setObjectName(_fromUtf8("cmdClose"))
        self.cmdShowReport = QtGui.QPushButton(HouseholdDisposableIncome)
        self.cmdShowReport.setGeometry(QtCore.QRect(410, 630, 111, 23))
        self.cmdShowReport.setObjectName(_fromUtf8("cmdShowReport"))
        self.listViewHCharacteristics = QtGui.QListView(HouseholdDisposableIncome)
        self.listViewHCharacteristics.setGeometry(QtCore.QRect(10, 260, 281, 271))
        self.listViewHCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewHCharacteristics.setObjectName(_fromUtf8("listViewHCharacteristics"))
        self.listViewPersonalCharacteristics = QtGui.QListView(HouseholdDisposableIncome)
        self.listViewPersonalCharacteristics.setGeometry(QtCore.QRect(310, 260, 311, 271))
        self.listViewPersonalCharacteristics.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listViewPersonalCharacteristics.setObjectName(_fromUtf8("listViewPersonalCharacteristics"))
        self.label_4 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 141, 20))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_5.setGeometry(QtCore.QRect(310, 240, 181, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.line_5 = QtGui.QFrame(HouseholdDisposableIncome)
        self.line_5.setGeometry(QtCore.QRect(0, 530, 631, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.treeViewHouseholds = QtGui.QTreeView(HouseholdDisposableIncome)
        self.treeViewHouseholds.setGeometry(QtCore.QRect(10, 80, 611, 151))
        self.treeViewHouseholds.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.treeViewHouseholds.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.treeViewHouseholds.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.treeViewHouseholds.setObjectName(_fromUtf8("treeViewHouseholds"))
        self.cmdSaveDataTable = QtGui.QPushButton(HouseholdDisposableIncome)
        self.cmdSaveDataTable.setGeometry(QtCore.QRect(294, 630, 91, 23))
        self.cmdSaveDataTable.setObjectName(_fromUtf8("cmdSaveDataTable"))
        self.cmbReportType = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbReportType.setGeometry(QtCore.QRect(120, 40, 281, 22))
        self.cmbReportType.setObjectName(_fromUtf8("cmbReportType"))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.cmbReportType.addItem(_fromUtf8(""))
        self.label_2 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cmbOrderCriteria1 = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbOrderCriteria1.setGeometry(QtCore.QRect(10, 580, 101, 22))
        self.cmbOrderCriteria1.setObjectName(_fromUtf8("cmbOrderCriteria1"))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.cmbOrderCriteria1.addItem(_fromUtf8(""))
        self.frame_2 = QtGui.QFrame(HouseholdDisposableIncome)
        self.frame_2.setGeometry(QtCore.QRect(430, 580, 181, 21))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.opt2Ascending_2 = QtGui.QRadioButton(self.frame_2)
        self.opt2Ascending_2.setGeometry(QtCore.QRect(10, 0, 82, 17))
        self.opt2Ascending_2.setObjectName(_fromUtf8("opt2Ascending_2"))
        self.opt2Descending_2 = QtGui.QRadioButton(self.frame_2)
        self.opt2Descending_2.setGeometry(QtCore.QRect(100, 0, 82, 17))
        self.opt2Descending_2.setObjectName(_fromUtf8("opt2Descending_2"))
        self.label_8 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_8.setGeometry(QtCore.QRect(10, 540, 241, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.line_2 = QtGui.QFrame(HouseholdDisposableIncome)
        self.line_2.setGeometry(QtCore.QRect(0, 600, 631, 20))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.frame = QtGui.QFrame(HouseholdDisposableIncome)
        self.frame.setGeometry(QtCore.QRect(130, 580, 171, 21))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.opt1Ascending_2 = QtGui.QRadioButton(self.frame)
        self.opt1Ascending_2.setGeometry(QtCore.QRect(10, 0, 111, 17))
        self.opt1Ascending_2.setObjectName(_fromUtf8("opt1Ascending_2"))
        self.opt1Descending_2 = QtGui.QRadioButton(self.frame)
        self.opt1Descending_2.setGeometry(QtCore.QRect(90, 0, 82, 17))
        self.opt1Descending_2.setObjectName(_fromUtf8("opt1Descending_2"))
        self.line_3 = QtGui.QFrame(HouseholdDisposableIncome)
        self.line_3.setGeometry(QtCore.QRect(0, 550, 631, 20))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.line = QtGui.QFrame(HouseholdDisposableIncome)
        self.line.setGeometry(QtCore.QRect(300, 560, 20, 51))
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_7 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_7.setGeometry(QtCore.QRect(320, 560, 111, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cmbOrderCriteria2 = QtGui.QComboBox(HouseholdDisposableIncome)
        self.cmbOrderCriteria2.setGeometry(QtCore.QRect(320, 580, 101, 22))
        self.cmbOrderCriteria2.setObjectName(_fromUtf8("cmbOrderCriteria2"))
        self.label_6 = QtGui.QLabel(HouseholdDisposableIncome)
        self.label_6.setGeometry(QtCore.QRect(10, 560, 111, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))

        self.retranslateUi(HouseholdDisposableIncome)
        QtCore.QMetaObject.connectSlotsByName(HouseholdDisposableIncome)

    def retranslateUi(self, HouseholdDisposableIncome):
        HouseholdDisposableIncome.setWindowTitle(QtGui.QApplication.translate("HouseholdDisposableIncome", "Report: Households by Income Source", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdClose.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Close", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdShowReport.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Show Report", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Household Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Personal Characteristics", None, QtGui.QApplication.UnicodeUTF8))
        self.cmdSaveDataTable.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Save Data Table", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(0, QtGui.QApplication.translate("HouseholdDisposableIncome", "Disposable Income - Raw", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(1, QtGui.QApplication.translate("HouseholdDisposableIncome", "Disposable Income - Standardised", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbReportType.setItemText(2, QtGui.QApplication.translate("HouseholdDisposableIncome", "Living Threshold", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Report Type", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(0, QtGui.QApplication.translate("HouseholdDisposableIncome", "Household Number", None, QtGui.QApplication.UnicodeUTF8))
        self.cmbOrderCriteria1.setItemText(1, QtGui.QApplication.translate("HouseholdDisposableIncome", "Household Name", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Ascending_2.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt2Descending_2.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Report Data Sort Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Ascending_2.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Ascending", None, QtGui.QApplication.UnicodeUTF8))
        self.opt1Descending_2.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "Descending", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "2nd Ordering Criteria", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("HouseholdDisposableIncome", "1st Ordering Criteria", None, QtGui.QApplication.UnicodeUTF8))

